<?php

namespace lujie\ar\snapshot\behaviors\tests\unit\fixtures\models;

/**
 * This is the model class for table "{{%test_item}}".
 *
 * @property string $test_item_id
 * @property string $snapshot_id
 * @property string $item_no
 * @property string $item_name
 * @property int $status
 * @property int $updated_at
 */
class TestItem extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%test_item}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['snapshot_id', 'status'], 'integer'],
            [['item_no', 'item_name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'test_item_id' => 'Test Item ID',
            'snapshot_id' => 'Snapshot ID',
            'item_no' => 'Item No',
            'item_name' => 'Item Name',
            'status' => 'Status',
        ];
    }

    public function beforeSave($insert)
    {
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
