<?php

namespace lujie\amazon\sp\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
*/
class InvoicesApiModel20240619 extends \lujie\amazon\sp\BaseAmazonSPClient
{

                
    /**
     * @description Returns marketplace-dependent schemas and their respective set of possible values.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The marketplace identifier.
     * @return array
     *      - *invoicesAttributes* - 
     */
    public function getInvoicesAttributes(array $query): array
    {
        return $this->api(array_merge(["/tax/invoices/2024-06-19/attributes"], $query));
    }
                    
    /**
     * @description Returns the invoice document's ID and URL. Use the URL to download the ZIP file, which contains the invoices from the corresponding `createInvoicesExport` request.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.0167 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param string $invoicesDocumentId The export document identifier.
     * @return array
     *      - *invoicesDocument* - 
     */
    public function getInvoicesDocument(string $invoicesDocumentId): array
    {
        return $this->api("/tax/invoices/2024-06-19/documents/{$invoicesDocumentId}");
    }
                    
    /**
     * @description Creates an invoice export request.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.167 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $data 
     * @return array
     *      - *exportId* - string
     *          - The export identifier.
     */
    public function createInvoicesExport(array $data): array
    {
        return $this->api("/tax/invoices/2024-06-19/exports", 'POST', $data);
    }
            
    /**
     * @description Returns invoice exports details for exports that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The returned exports match the specified marketplace.
     *      - *dateStart* - string - optional
     *          - The earliest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 30 days ago.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices to return in a single call.

Minimum: 1

Maximum: 100
     *      - *dateEnd* - string - optional
     *          - The latest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default value is the time of the request.
     *      - *status* - string - optional
     *          - Return exports matching the status specified. 
     * @return Iterator
     *      - *exports* - array
     *          - A list of exports.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function eachInvoicesExports(array $query): Iterator
    {
        return $this->eachInternal('getInvoicesExports', func_get_args());
    }
        
    /**
     * @description Returns invoice exports details for exports that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The returned exports match the specified marketplace.
     *      - *dateStart* - string - optional
     *          - The earliest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 30 days ago.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices to return in a single call.

Minimum: 1

Maximum: 100
     *      - *dateEnd* - string - optional
     *          - The latest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default value is the time of the request.
     *      - *status* - string - optional
     *          - Return exports matching the status specified. 
     * @return Iterator
     *      - *exports* - array
     *          - A list of exports.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function batchInvoicesExports(array $query): Iterator
    {
        return $this->batchInternal('getInvoicesExports', func_get_args());
    }
    
    /**
     * @description Returns invoice exports details for exports that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The returned exports match the specified marketplace.
     *      - *dateStart* - string - optional
     *          - The earliest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 30 days ago.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices to return in a single call.

Minimum: 1

Maximum: 100
     *      - *dateEnd* - string - optional
     *          - The latest export creation date and time for exports that you want to include in the response. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default value is the time of the request.
     *      - *status* - string - optional
     *          - Return exports matching the status specified. 
     * @return array
     *      - *exports* - array
     *          - A list of exports.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function getInvoicesExports(array $query): array
    {
        return $this->api(array_merge(["/tax/invoices/2024-06-19/exports"], $query));
    }
                    
    /**
     * @description Returns invoice export details (including the `exportDocumentId`, if available) for the export that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 15 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param string $exportId The unique identifier for the export.
     * @return array
     *      - *export* - 
     */
    public function getInvoicesExport(string $exportId): array
    {
        return $this->api("/tax/invoices/2024-06-19/exports/{$exportId}");
    }
                
    /**
     * @description Returns invoice details for the invoices that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *transactionIdentifierName* - string - optional
     *          - The name of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierId` field.Use the `getInvoicesAttributes` operation to check `transactionIdentifierName` options.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices you want to return in a single call.

Minimum: 1

Maximum: 200
     *      - *dateEnd* - string - optional
     *          - The latest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is the current date-time.
     *      - *marketplaceId* - string - required
     *          - The response includes only the invoices that match the specified marketplace.
     *      - *transactionType* - string - optional
     *          - The marketplace-specific classification of the transaction type for which the invoice was created. Use the `getInvoicesAttributes` operation to check `transactionType` options.
     *      - *transactionIdentifierId* - string - optional
     *          - The ID of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierName` field.
     *      - *dateStart* - string - optional
     *          - The earliest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 24 hours prior to the time of the request.
     *      - *series* - string - optional
     *          - Return invoices with the specified series number.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *sortOrder* - string - optional
     *          - Sort the invoices in the response in ascending or descending order.
     *      - *invoiceType* - string - optional
     *          - The marketplace-specific classification of the invoice type. Use the `getInvoicesAttributes` operation to check `invoiceType` options.
     *      - *statuses* - array - optional
     *          - A list of statuses that you can use to filter invoices. Use the `getInvoicesAttributes` operation to check invoice status options.

Min count: 1
     *      - *externalInvoiceId* - string - optional
     *          - Return invoices that match this external ID. This is typically the Government Invoice ID.
     *      - *sortBy* - string - optional
     *          - The attribute by which you want to sort the invoices in the response.
     * @return Iterator
     *      - *invoices* - array
     *          - A list of invoices.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function eachInvoices(array $query): Iterator
    {
        return $this->eachInternal('getInvoices', func_get_args());
    }
        
    /**
     * @description Returns invoice details for the invoices that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *transactionIdentifierName* - string - optional
     *          - The name of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierId` field.Use the `getInvoicesAttributes` operation to check `transactionIdentifierName` options.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices you want to return in a single call.

Minimum: 1

Maximum: 200
     *      - *dateEnd* - string - optional
     *          - The latest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is the current date-time.
     *      - *marketplaceId* - string - required
     *          - The response includes only the invoices that match the specified marketplace.
     *      - *transactionType* - string - optional
     *          - The marketplace-specific classification of the transaction type for which the invoice was created. Use the `getInvoicesAttributes` operation to check `transactionType` options.
     *      - *transactionIdentifierId* - string - optional
     *          - The ID of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierName` field.
     *      - *dateStart* - string - optional
     *          - The earliest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 24 hours prior to the time of the request.
     *      - *series* - string - optional
     *          - Return invoices with the specified series number.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *sortOrder* - string - optional
     *          - Sort the invoices in the response in ascending or descending order.
     *      - *invoiceType* - string - optional
     *          - The marketplace-specific classification of the invoice type. Use the `getInvoicesAttributes` operation to check `invoiceType` options.
     *      - *statuses* - array - optional
     *          - A list of statuses that you can use to filter invoices. Use the `getInvoicesAttributes` operation to check invoice status options.

Min count: 1
     *      - *externalInvoiceId* - string - optional
     *          - Return invoices that match this external ID. This is typically the Government Invoice ID.
     *      - *sortBy* - string - optional
     *          - The attribute by which you want to sort the invoices in the response.
     * @return Iterator
     *      - *invoices* - array
     *          - A list of invoices.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function batchInvoices(array $query): Iterator
    {
        return $this->batchInternal('getInvoices', func_get_args());
    }
    
    /**
     * @description Returns invoice details for the invoices that match the filters that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.1 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param array $query
     *      - *transactionIdentifierName* - string - optional
     *          - The name of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierId` field.Use the `getInvoicesAttributes` operation to check `transactionIdentifierName` options.
     *      - *pageSize* - integer - optional
     *          - The maximum number of invoices you want to return in a single call.

Minimum: 1

Maximum: 200
     *      - *dateEnd* - string - optional
     *          - The latest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is the current date-time.
     *      - *marketplaceId* - string - required
     *          - The response includes only the invoices that match the specified marketplace.
     *      - *transactionType* - string - optional
     *          - The marketplace-specific classification of the transaction type for which the invoice was created. Use the `getInvoicesAttributes` operation to check `transactionType` options.
     *      - *transactionIdentifierId* - string - optional
     *          - The ID of the transaction identifier filter. If you provide a value for this field, you must also provide a value for the `transactionIdentifierName` field.
     *      - *dateStart* - string - optional
     *          - The earliest invoice creation date for invoices that you want to include in the response. Dates are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format. The default is 24 hours prior to the time of the request.
     *      - *series* - string - optional
     *          - Return invoices with the specified series number.
     *      - *nextToken* - string - optional
     *          - The response includes `nextToken` when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the operation with this token and include the same arguments as the call that produced the token. To get a complete list, call this operation until `nextToken` is null. Note that this operation can return empty pages.
     *      - *sortOrder* - string - optional
     *          - Sort the invoices in the response in ascending or descending order.
     *      - *invoiceType* - string - optional
     *          - The marketplace-specific classification of the invoice type. Use the `getInvoicesAttributes` operation to check `invoiceType` options.
     *      - *statuses* - array - optional
     *          - A list of statuses that you can use to filter invoices. Use the `getInvoicesAttributes` operation to check invoice status options.

Min count: 1
     *      - *externalInvoiceId* - string - optional
     *          - Return invoices that match this external ID. This is typically the Government Invoice ID.
     *      - *sortBy* - string - optional
     *          - The attribute by which you want to sort the invoices in the response.
     * @return array
     *      - *invoices* - array
     *          - A list of invoices.
     *      - *nextToken* - string
     *          - This token is returned when the number of results exceeds the specified `pageSize` value. To get the next page of results, call the `getInvoices` operation and include this token with the previous call parameters.
     */
    public function getInvoices(array $query): array
    {
        return $this->api(array_merge(["/tax/invoices/2024-06-19/invoices"], $query));
    }
                    
    /**
     * @description Returns invoice data for the specified invoice. This operation returns only a subset of the invoices data; refer to the response definition to get all the possible attributes.
To get the full invoice, use the `createInvoicesExport` operation to start an export request.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 15 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag invoices
     * @param string $invoiceId The invoice identifier.
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The marketplace from which you want the invoice.
     * @return array
     *      - *invoice* - 
     */
    public function getInvoice(string $invoiceId, array $query): array
    {
        return $this->api(array_merge(["/tax/invoices/2024-06-19/invoices/{$invoiceId}"], $query));
    }
    
}
