<?php

namespace lujie\amazon\sp\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class VendorDirectFulfillmentOrdersV1Const
{
        public const ORDER_DETAILS_ORDER_STATUS_NEW = 'NEW';
        public const ORDER_DETAILS_ORDER_STATUS_SHIPPED = 'SHIPPED';
        public const ORDER_DETAILS_ORDER_STATUS_ACCEPTED = 'ACCEPTED';
        public const ORDER_DETAILS_ORDER_STATUS_CANCELLED = 'CANCELLED';
        
        public const TAX_REGISTRATION_DETAILS_TAX_REGISTRATION_TYPE_VAT = 'VAT';
        public const TAX_REGISTRATION_DETAILS_TAX_REGISTRATION_TYPE_GST = 'GST';
        
        public const ITEM_QUANTITY_UNIT_OF_MEASURE_EACH = 'Each';
        
        public const TAX_DETAILS_TYPE_CONSUMPTION = 'CONSUMPTION';
        public const TAX_DETAILS_TYPE_GST = 'GST';
        public const TAX_DETAILS_TYPE_MW_ST = 'MwSt.';
        public const TAX_DETAILS_TYPE_PST = 'PST';
        public const TAX_DETAILS_TYPE_TOTAL = 'TOTAL';
        public const TAX_DETAILS_TYPE_TVA = 'TVA';
        public const TAX_DETAILS_TYPE_VAT = 'VAT';
        
        public const STATUS_NEW = 'NEW';
        public const STATUS_SHIPPED = 'SHIPPED';
        public const STATUS_ACCEPTED = 'ACCEPTED';
        public const STATUS_CANCELLED = 'CANCELLED';
        
        public const SORT_ORDER_ASC = 'ASC';
        public const SORT_ORDER_DESC = 'DESC';
        
}
