<?php

namespace lujie\amazon\advertising\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description Amazon DSP users can now use the hashed records API through the Amazon Advertising API to match Amazon shoppers with their hashed customer records including name, email, mobile, address, and zip code. Advertisers can further use the data provider APIs (https://advertising.amazon.com/API/docs/en-us/data-provider/openapi#/) to programmatically create audiences for use in their campaigns by their owned or sourced hashed customer records.
*/
class HashedRecordsV3 extends \lujie\amazon\advertising\BaseAmazonAdvertisingClient
{

                
    /**
     * @description Saves a batch of hashed personally-identifiable information (PII) records to be matched with Amazon identities for future use.  All inputs must be properly normalized and SHA-256 hashed as defined [in the documentation](https://advertising.amazon.com/help/GCCXMZYCK4RXWS6C).     * @tag Hashed Records
     * @param array $data Hashed PII records to be matched with Amazon identities for future use.  All inputs must be properly normalized and SHA-256 hashed as defined [in the documentation](https://advertising.amazon.com/help/GCCXMZYCK4RXWS6C). Max input size 5MB.
     */
    public function uploadHashedRecords(array $data, string $contentType = 'application/vnd.dpuploadhashedrecordsrequest.v3+json'): void
    {
        $this->api("/dp/records/hashed", 'POST', $data, ['content-type' => $contentType, 'accept' => $contentType]);
    }
    
}
