<?php

namespace lujie\amazon\advertising\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description 
*/
class PreModerationV3 extends \lujie\amazon\advertising\BaseAmazonAdvertisingClient
{

                
    /**
     * @description This API will be accepting different components of the ad/page and will be automatically validating the components and send back the policy violations if any. We recommend to send all components of the same entity to be sent together. It will make us better detect any policy violation if present. This will increase the Time to go live for the entity. In one request please don't send the components of more than one entity.     * @tag Pre Moderation
     * @param array $data Request body for preModeration API.
     *      - *recordId* - string
     *          - Id of the brand/advertiser.
     *      - *asinComponents* - array
     *          - Asin components which needs to be pre moderated.
     *      - *adProgram* - string
     *          - Type of Ad program to which this pre moderation components belong to.
     *      - *locale* - string
     *          - Specifying locale will translate the premoderation message into that locale's associated language. 
 
 | Locale | Language (ISO 639) | Country (ISO 3166) | 
 |-----|-----|-------| 
 | ar-AE | Arabic (ar) | United Arab Emirates (AE) | 
 | zh-CN | Chinese (zh) | China (CN) | 
 | nl-NL | Dutch (nl) | Netherlands (NL) | 
 | en-AE | English (en) | United Arab Emirates (AE) | 
 | en-AU | English (en) | Australia (AU) | 
 | en-CA | English (en) | Canada (CA) | 
 | en-IN | English (en) | India (IN) | 
 | en-JP | English (en) | Japan (JP) | 
 | en-NL | English (en) | Netherlands (NL) | 
 | en-SA | English (en) | Saudi Arabia (SA) | 
 | en-GB | English (en) | United Kingdom (GB) | 
 | en-US | English (en) | United States (US) | 
 | fr-CA | French (fr) | Canada (CA) | 
 | fr-FR | French (fr) | France (FR) | 
 | de-DE | German (de) | Germany (DE) | 
 | it-IT | Italian (it) | Italy (IT) | 
 | ja-JP | Japanese (ja) | Japan (JP) | 
 | ko-KR | Korean (ko) | South Korea (KR) | 
 | pt-BR | Portuguese (pt) | Brazil (BR) | 
 | es-ES | Spanish (es) | Spain (ES) | 
 | es-US | Spanish (es) | United States (US) | 
 | es-MX | Spanish (es) | Mexico (MX) | 
 | tr-TR | Turkish (tr) | Turkey (TR) | 
 
     *      - *imageComponents* - array
     *          - Image components which needs to be pre moderated.
     *      - *dateComponents* - array
     *          - Date components which needs to be pre moderated.
     *      - *textComponents* - array
     *          - Text components which needs to be pre moderated.
     *      - *videoComponents* - array
     *          - Video components which needs to be pre moderated.
     * @return array
     *      - *recordId* - string
     *          - Id of the brand/advertiser.
     *      - *asinComponents* - array
     *          - Pre moderation result of the asin components. It will have information regarding the policy violations present if any.
     *      - *preModerationId* - string
     *          - Unique Id for the moderation Request.
     *      - *adProgram* - string
     *          - Type of Ad program to which the pre moderation components belong to.
     *      - *locale* - string
     *          - Locale value that was passed in request.
     *      - *imageComponents* - array
     *          - Pre moderation result of the image components. It will have information regarding the policy violations present if any.
     *      - *dateComponents* - array
     *          - Pre moderation result of the date components. It will have information regarding the policy violations present if any.
     *      - *textComponents* - array
     *          - Pre moderation result of the text components. It will have information regarding the policy violations present if any.
     *      - *videoComponents* - array
     *          - Pre moderation result of the video components. It will have information regarding the policy violations present if any.
     */
    public function preModeration(array $data, string $contentType = 'application/json'): array
    {
        return $this->api("/preModeration", 'POST', $data, ['content-type' => $contentType, 'accept' => $contentType]);
    }
    
}
