<?php

namespace lujie\amazon\advertising\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description Create test advertising account for 3P API integrators
*/
class AdvertisingTestAccountV3 extends \lujie\amazon\advertising\BaseAmazonAdvertisingClient
{

                
    /**
     * @description Submit a account creation request. You can create up to 1 test account type per marketplace.     * @tag Create test account
     * @param array $data 
     *      - *countryCode* - string
     *          - Country code of the test  account.
     *      - *accountMetaData* - 
     *      - *accountType* - string
     *          - Type of test account.
     * @return array
     *      - *requestId* - string
     *          - request id.
     */
    public function createAccount(array $data, string $contentType = 'application/json'): array
    {
        return $this->api("/testAccounts", 'POST', $data, ['content-type' => $contentType, 'accept' => $contentType]);
    }
                
    /**
     * @description API to get Account information.     * @tag Get test account information 
     * @param array $query
     *      - *requestId* - string - optional
     *          - request id.
     * @return array
     */
    public function getAccountInformation(array $query = [], string $contentType = 'application/json'): array
    {
        return $this->api(array_merge(["/testAccounts"], $query), ['content-type' => $contentType, 'accept' => $contentType]);
    }
    
}
