<?php

namespace lujie\amazon\advertising\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class AdvertisingTestAccountV3Const
{
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_US = 'US';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_CA = 'CA';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_MX = 'MX';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_BR = 'BR';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_UK = 'UK';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_DE = 'DE';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_FR = 'FR';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_ES = 'ES';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_IT = 'IT';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_JP = 'JP';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_AU = 'AU';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_AE = 'AE';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_SA = 'SA';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_NL = 'NL';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_SE = 'SE';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_TR = 'TR';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_PL = 'PL';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_BE = 'BE';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_EG = 'EG';
        public const CREATE_ACCOUNT_REQUEST_COUNTRY_CODE_SG = 'SG';
        
        public const CREATE_ACCOUNT_REQUEST_ACCOUNT_TYPE_VENDOR = 'VENDOR';
        public const CREATE_ACCOUNT_REQUEST_ACCOUNT_TYPE_AUTHOR = 'AUTHOR';
        
}
