<?php

namespace lujie\amazon\advertising\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class AmazonMarketingStreamV3Const
{
        public const SUBSCRIPTION_ENTITY_STATUS_PROVISIONING = 'PROVISIONING';
        public const SUBSCRIPTION_ENTITY_STATUS_PENDING_CONFIRMATION = 'PENDING_CONFIRMATION';
        public const SUBSCRIPTION_ENTITY_STATUS_ACTIVE = 'ACTIVE';
        public const SUBSCRIPTION_ENTITY_STATUS_ARCHIVED = 'ARCHIVED';
        public const SUBSCRIPTION_ENTITY_STATUS_FAILED_CONFIRMATION = 'FAILED_CONFIRMATION';
        public const SUBSCRIPTION_ENTITY_STATUS_SUSPENDED = 'SUSPENDED';
        public const SUBSCRIPTION_ENTITY_STATUS_FAILED_PROVISIONING = 'FAILED_PROVISIONING';
        
        public const UPDATE_ENTITY_STATUS_ARCHIVED = 'ARCHIVED';
        
}
