<?php

namespace lujie\plentyMarkets\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The plentymarkets REST API expands the functionality of the plentymarkets CMS and allows access to resources, i.e. data records, via unique URI paths
*/
class Blog extends \lujie\plentyMarkets\BasePlentyMarketsRestClient
{

                
    /**
     * @description Creates a new blog post.
     * @tag Blog
     * @return array
     *      - *id* - string
     *      - *plentyIdHash* - string
     *      - *data* - string
     */
    public function createBlogsPost(): array
    {
        return $this->api("/rest/blogs/post", 'POST');
    }
                    
    /**
     * @description Deletes a blog post based on its ID.
     * @tag Blog
     * @param int $postId 
     */
    public function deleteBlogsPostByPostId(int $postId): void
    {
        $this->api("/rest/blogs/post/{$postId}", 'DELETE');
    }
                
    /**
     * @description Gets a blog post based on its ID.
     * @tag Blog
     * @param int $postId 
     * @return array
     *      - *id* - string
     *      - *plentyIdHash* - string
     *      - *data* - string
     */
    public function getBlogsPostByPostId(int $postId): array
    {
        return $this->api("/rest/blogs/post/{$postId}");
    }
                
    /**
     * @description Updates a blog post based on its ID.
     * @tag Blog
     * @param int $postId 
     * @return array
     *      - *id* - string
     *      - *plentyIdHash* - string
     *      - *data* - string
     */
    public function updateBlogsPostByPostId(int $postId): array
    {
        return $this->api("/rest/blogs/post/{$postId}", 'PUT');
    }
                    
    /**
     * @description Gets a paginated list of blog posts.
     * @tag Blog
     * @return array
     */
    public function getBlogsPosts(): array
    {
        return $this->api("/rest/blogs/posts");
    }
    
}
