<?php

namespace lujie\ebay\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><span class="tablenote"><b>Note:</b> This is a <a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> API available only to select developers approved by business units.</span><br><br>The Order API provides interfaces that let shoppers pay for items. It also returns payment and shipping status of the order.
*/
class BuyOrderV2 extends \lujie\ebay\BaseEbayRestClient
{

    public $apiBaseUrl = 'https://api.ebay.com/buy/order/v2';

                
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method adds a coupon to an eBay guest checkout session and applies it to all the eligible items in the order.<br><br>The <b>checkoutSessionId</b> is passed in as a URI parameter and is required. The redemption code of the coupon is in the payload and is also required.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $data The container for the fields used to apply a coupon to a guest checkout session.
     *      - *redemptionCode* - string
     *          - The redemption code of the coupon.<br><br><b>Maximum:</b> One redemption code per order
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function applyGuestCoupon(string $checkoutSessionId, array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}/apply_coupon", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method returns the details of the specified guest checkout session. The <b>checkoutSessionId</b> is passed in as a URI parameter and is required. This method has no request payload.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function getGuestCheckoutSession(string $checkoutSessionId, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}", 'GET', [], $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method creates an eBay guest checkout session, which is the first step in performing a checkout. The method returns a <b>checkoutSessionId</b> that you use as a URI parameter in subsequent guest checkout methods.  <br><br><span class="tablenote"><b>Note:</b> This method also returns the <b>X-EBAY-SECURITY-SIGNATURE</b> response header, which is a token that is used to launch the Checkout with eBay widget. The Checkout with eBay widget allows eBay guests to pay for items without leaving your site. For details about the Checkout with eBay widget, see <a href="/api-docs/buy/static/api-order.html#Integrat">Integrating the Checkout with eBay button</a>. </span>   <br><br>Also see <a href="/api-docs/buy/static/ref-buy-negative-testing.html">Negative Testing Using Stubs</a> for information on how to emulate error conditions for this  method using stubs.<br><br><span class="tablenote"><font color="006600"><b>TIP:</b></font> To test the entire checkout flow, you might need a "test" credit card. You can generate a credit card number from <a href="http://www.getcreditcardnumbers.com" target="_blank">http://www.getcreditcardnumbers.com</a>.</span><br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param array $data The container for the fields used by the <b>initiateGuestCheckoutSession</b> method.
     *      - *contactEmail* - string
     *          - The buyer's email address.
     *      - *lineItemInputs* - array
     *          - An array used to define the line item(s) and desired quantity for an eBay guest checkout session.<br><br><b>Maximum:</b> 10 line items
     *      - *shippingAddress* - 
     *          - A container that defines the shipping address for an eBay guest checkout session.<br><br>The Order API supports only domestic shipping. For example, an item purchased on the <code>EBAY_DE</code> marketplace can be shipped only to an address in Germany.<br><br><span class="tablenote"><b>Note:</b> If the address cannot be validated, a warning message is  returned along with the response.</span>
     * @param array $headers
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur.<br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function initiateGuestCheckoutSession(array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/initiate", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method removes a coupon from an eBay guest checkout session. The <b>checkoutSessionId</b> is passed in as a URI parameter and is required. The redemption code of the coupon is specified in the payload and is also required.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $data The container for the fields used by the <b>removeGuestCoupon</b> method.
     *      - *redemptionCode* - string
     *          - The redemption code of the coupon.<br><br><b>Maximum:</b> One redemption code per order
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function removeGuestCoupon(string $checkoutSessionId, array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}/remove_coupon", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method changes the quantity of the specified line item in an eBay guest checkout session.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $data The container for the fields used by the <b>updateGuestQuantity</b> method.
     *      - *lineItemId* - string
     *          - A unique eBay-assigned ID value that identifies a line item in a purchase order.
     *      - *quantity* - integer
     *          - The number of individual items ordered in this line item, as specified by the buyer.
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function updateGuestQuantity(string $checkoutSessionId, array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}/update_quantity", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method changes the shipping address for the order in an eBay guest checkout session. All the line items in an order must be shipped to the same address, but the shipping method can be specific to the line item.<br><br><span class="tablenote"><b>Note:</b> If the address submitted cannot be validated, a warning message will be returned. This does not prevent the method from executing, but you may want to verify the address.</span><br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $data The container for the fields used by the <b>updateGuestShippingAddress</b> method.
     *      - *addressLine1* - string
     *          - The first line of the street address where the item is being shipped.<br><br><b>Maximum:</b><ul><li>40 characters for AU, CA, and US marketplaces</li><li>35 characters for DE and GB marketplaces</li><li>50 characters for all other marketplaces</li></ul>
     *      - *addressLine2* - string
     *          - The second line of the street address where the item is being shipped. This optional field can be used for information such as 'Suite Number' or 'Apt Number'.<br><br><b>Maximum:</b><ul><li>40 characters for AU, CA, and US marketplaces</li><li>35 characters for DE and GB marketplaces</li><li>50 characters for all other marketplaces</li></ul>
     *      - *city* - string
     *          - The city of the address where the item is being shipped.
     *      - *country* - string
     *          - The two letter code representing the country of the address. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/order/types/bas:CountryCodeEnum'>eBay API documentation</a>
     *      - *county* - string
     *          - The county of the address where the item is being shipped.
     *      - *phoneNumber* - string
     *          - The phone number of the person receiving the package.<br><br><span class="tablenote"><b>Note:</b> It is highly recommended that when entering the phone number you include the country code.<br><br>For example, if a US phone number is <code>4********4</code>, you would enter <code>+14********4</code>. If you do not include this code, the service will use the country specified in the <b>country</b> field.<br><br>You can find the country code at <a href="https://countrycode.org/">https://countrycode.org</a>.</span>
     *      - *postalCode* - string
     *          - The postal code of the address where the item is being shipped.<br><br><span class="tablenote"><b>Note:</b> This is optional when shipping to EBAY_HK (Hong Kong).</span>
     *      - *recipient* - 
     *          - The name of the person receiving the package.
     *      - *stateOrProvince* - string
     *          - The state or province of the address.<br><br><span class="tablenote"><b>Note:</b> For the US marketplace, this is a two-character value. For a list of valid values, see <a href="https://www.ups.com/worldshiphelp/WS15/ENU/AppHelp/Codes/State_Province_Codes.htm">US State and Canada Province Codes</a>. </span>
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function updateGuestShippingAddress(string $checkoutSessionId, array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}/update_shipping_address", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method changes the shipping method for the specified line item in an eBay guest checkout session. The shipping option can be set for each line item. This gives the shopper the ability choose the cost of shipping for each line item.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_checkout_session
     * @param string $checkoutSessionId The eBay-assigned session ID, for a specific eBay marketplace, that is returned by the <b> initiateGuestCheckoutSession</b> method.<br><br><span class="tablenote"><b>Note:</b> When using this ID, the X-EBAY-C-MARKETPLACE-ID value and developer App ID must be the same as that used when this guest checkout session was created. See <a href="/api-docs/buy/order/overview.html#checkout-restriction">Checkout session restrictions</a> in the Buy Integration Guide for details.</span>
     * @param array $data The container for the fields used by the <b>updateGuestShippingOption</b> method.
     *      - *lineItemId* - string
     *          - A unique eBay-assigned ID value that identifies the line item in a checkout session.
     *      - *shippingOptionId* - string
     *          - A unique ID for the selected shipping option/method.
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - required
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *Content-Type* - string - required
     *          - This header indicates the format of the request body provided by the client. It's value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *appliedCoupons* - array
     *          - A container that returns the information for the coupons that were applied in the guest checkout session.
     *      - *checkoutSessionId* - string
     *          - The eBay-assigned guest checkout session ID. This ID is created after a successful <b>initiateGuestCheckoutSession</b> call.
     *      - *lineItems* - array
     *          - An array of line items associated with the guest checkout session.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *shippingAddress* - 
     *          - A container that returns the address to which the purchase order will be shipped.
     *      - *warnings* - array
     *          - An array of errors or warnings that were generated during the method processing.
     */
    public function updateGuestShippingOption(string $checkoutSessionId, array $data, array $headers): array
    {
        return $this->api("/guest_checkout_session/{$checkoutSessionId}/update_shipping_option", 'POST', $data, $headers);
    }
                    
    /**
     * @description <span class="tablenote"><b>Note:</b> The Order API (v2) currently only supports the guest payment/checkout flow. If you need to support member payment/checkout flow, use the <a href="/api-docs/buy/order_v1/resources/methods">v1_beta version</a> of the Order API.</span><br><br><a href="https://developer.ebay.com/api-docs/static/versioning.html#limited" target="_blank"><img src="/cms/img/docs/partners-api.svg" class="legend-icon partners-icon"  alt="Limited Release" title="Limited Release" />(Limited Release)</a> This method is only available to select developers approved by business units.<br><br>This method retrieves the details about a specific guest purchase order. It returns the line items, including purchase  order status, dates created and modified, item quantity and listing data, payment and shipping information, and prices, taxes, discounts and credits.<br><br>The <b>purchaseOrderId</b> is passed in as a URI parameter and is required.<br><br><span class="tablenote"><b>Note:</b> The <b>purchaseOrderId</b> value is returned in the call-back URL that is sent through the new eBay pay widget. For more information about eBay managed payments and the new Order API payment flow, see <a href="/api-docs/buy/static/api-order.html">Order API</a> in the Buying Integration Guide.</span><br><br>You can use this method to not only get the details of a purchase order, but to check the value of the <a href="#response.purchaseOrderPaymentStatus">purchaseOrderPaymentStatus</a> field to determine if the order has been paid for. If the order has been paid for, this field will return <code>PAID</code>.<br><br>For a list of supported sites and other restrictions, see <a href="/api-docs/buy/order/overview.html#API">API Restrictions</a> in the Order API overview.
     * @tag guest_purchase_order
     * @param string $purchaseOrderId The unique identifier of a purchase order made by a guest buyer, for which details are to be retrieved.<br><br><span class="tablenote"><b>Note:</b> This value is returned in the response URL that is sent through the new eBay pay widget. For more information about eBay managed payments and the new Order API payment flow, see <a href="/api-docs/buy/static/api-order.html">Order API</a> in the Buying Integration Guide.</span>
     * @param array $headers
     *      - *X-EBAY-C-MARKETPLACE-ID* - string - optional
     *          - This header identifies the eBay marketplace where the order will occur. For this method, this value must match the <b>X-EBAY-C-MARKETPLACE-ID</b> used when the associated checkout session was created. <br><br>See <a href="/api-docs/static/rest-request-components.html#marketpl " target="_blank ">HTTP request headers</a> for the marketplace ID values.
     *      - *X-EBAY-C-ENDUSERCTX* - string - optional
     *          - This header is used to specify the <b>deviceId</b> for the device/user attempting to make the call. It contains an alphanumeric string that allows a payment gateway to track an API call attempt and confirm that it is a verified payment attempt by a device/user.
     * @return array
     *      - *lineItems* - array
     *          - An array of line items in the order.
     *      - *pricingSummary* - 
     *          - A container that breaks down the costs for the order, including total cost, shipping cost, tax, fees, and any discounts.
     *      - *purchaseOrderCreationDate* - string
     *          - The creation date of the purchase order.
     *      - *purchaseOrderId* - string
     *          - The unique identifier of the purchase order.
     *      - *purchaseOrderPaymentStatus* - string
     *          - A container that returns the payment status for the purchase order. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/order/types/gct:PurchaseOrderPaymentStatusEnum'>eBay API documentation</a>
     *      - *purchaseOrderStatus* - string
     *          - An enumeration value that indicates the current status of the buyer's payment and any refund that applies to the purchase order. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/order/types/gct:PurchaseOrderStatusEnum'>eBay API documentation</a>
     *      - *refundedAmount* - 
     *          - The total amount of any refunds for the purchase order.
     *      - *warnings* - array
     *          - A container for any warning messages.
     */
    public function getGuestPurchaseOrder(string $purchaseOrderId, array $headers): array
    {
        return $this->api("/guest_purchase_order/{$purchaseOrderId}", 'GET', [], $headers);
    }
        
}
