<?php

namespace lujie\ebay\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The Charity API allows third-party developers to search for and access details on supported charitable organizations.
*/
class CommerceCharityV1 extends \lujie\ebay\EbayRestClient
{

    public $apiBaseUrl = 'https://api.ebay.com/commerce/charity/v1';

        
    /**
    * @description This call is used to retrieve detailed information about supported charitable organizations. It allows users to retrieve the details for a specific charitable organization using its charity organization ID.
    * @tag charity_org
        * @param string $charityOrgId The unique ID of the charitable organization.
    * @return array
    *      - *charityOrgId* - string
    *          - The ID of the charitable organization.
    *      - *description* - string
    *          - The description of the charitable organization.
    *      - *location* - 
    *          - The location details of the charitable organization.
    *      - *logoImage* - 
    *          - The logo of the charitable organization.
    *      - *missionStatement* - string
    *          - The mission statement of the charitable organization.
    *      - *name* - string
    *          - The name of the charitable organization.
    *      - *registrationId* - string
    *          - The registration ID for the charitable organization.<br /><br /><span class="tablenote"><span style="color:#004680"><strong>Note:</strong></span> For the US marketplace, this is the EIN.</span>
    *      - *website* - string
    *          - The link to the website for the charitable organization.
    */
    public function getCharityOrg(string $charityOrgId): array
    {
        return $this->api("/charity_org/{$charityOrgId}");
    }
                    
    /**
    * @description This call is used to search for supported charitable organizations. It allows users to search for a specific charitable organization, or for multiple charitable organizations, from a particular charitable domain and/or geographical region, or by using search criteria.<br /><br />The call returns paginated search results containing the charitable organizations that match the specified criteria.
    * @tag charity_org
        * @param array $query
    *      - *limit* - string - optional
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *offset* - string - optional
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *q* - string - optional
    *          - A query string that matches the keywords in name, mission statement, or description.
    *      - *registration_ids* - string - optional
    *          - A comma-separated list of charitable organization registration IDs.<br /><br /><span class="tablenote"><b>Note: </b>Do not specify this parameter for query-based searches. Specify either the <b>q</b> or <b>registration_ids</b> parameter, but not both.</span><br /><br /><b>Maximum Limit:</b> <code>20</code>
    * @return array
    *      - *charityOrgs* - array
    *          - The list of charitable organizations that match the search criteria.
    *      - *href* - string
    *          - The relative path to the current set of results.
    *      - *limit* - integer
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *next* - string
    *          - The relative path to the next set of results.
    *      - *offset* - integer
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *prev* - string
    *          - The relative path to the previous set of results.
    *      - *total* - integer
    *          - The total number of matches for the search criteria.
    */
    public function getCharityOrgs(array $query): array
    {
        return $this->api(array_merge(["/charity_org"], $query));
    }
    
    /**
    * @description This call is used to search for supported charitable organizations. It allows users to search for a specific charitable organization, or for multiple charitable organizations, from a particular charitable domain and/or geographical region, or by using search criteria.<br /><br />The call returns paginated search results containing the charitable organizations that match the specified criteria.
    * @tag charity_org
        * @param array $query
    *      - *limit* - string - optional
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *offset* - string - optional
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *q* - string - optional
    *          - A query string that matches the keywords in name, mission statement, or description.
    *      - *registration_ids* - string - optional
    *          - A comma-separated list of charitable organization registration IDs.<br /><br /><span class="tablenote"><b>Note: </b>Do not specify this parameter for query-based searches. Specify either the <b>q</b> or <b>registration_ids</b> parameter, but not both.</span><br /><br /><b>Maximum Limit:</b> <code>20</code>
    * @return Iterator
    *      - *charityOrgs* - array
    *          - The list of charitable organizations that match the search criteria.
    *      - *href* - string
    *          - The relative path to the current set of results.
    *      - *limit* - integer
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *next* - string
    *          - The relative path to the next set of results.
    *      - *offset* - integer
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *prev* - string
    *          - The relative path to the previous set of results.
    *      - *total* - integer
    *          - The total number of matches for the search criteria.
    */
    public function eachCharityOrgs(array $query): Iterator
    {
        return $this->eachInternal('getCharityOrgs', func_get_args());
    }
            /**
    * @description This call is used to search for supported charitable organizations. It allows users to search for a specific charitable organization, or for multiple charitable organizations, from a particular charitable domain and/or geographical region, or by using search criteria.<br /><br />The call returns paginated search results containing the charitable organizations that match the specified criteria.
    * @tag charity_org
        * @param array $query
    *      - *limit* - string - optional
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *offset* - string - optional
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *q* - string - optional
    *          - A query string that matches the keywords in name, mission statement, or description.
    *      - *registration_ids* - string - optional
    *          - A comma-separated list of charitable organization registration IDs.<br /><br /><span class="tablenote"><b>Note: </b>Do not specify this parameter for query-based searches. Specify either the <b>q</b> or <b>registration_ids</b> parameter, but not both.</span><br /><br /><b>Maximum Limit:</b> <code>20</code>
    * @return Iterator
    *      - *charityOrgs* - array
    *          - The list of charitable organizations that match the search criteria.
    *      - *href* - string
    *          - The relative path to the current set of results.
    *      - *limit* - integer
    *          - The number of items, from the result set, returned in a single page.<br /><br /><b>Valid Values:</b> <code>1-100</code><br /><br /><b>Default:</b> <code>20</code>
    *      - *next* - string
    *          - The relative path to the next set of results.
    *      - *offset* - integer
    *          - The number of items that will be skipped in the result set. This is used with the <b>limit</b> field to control the pagination of the output.<br /><br />For example, if the <b>offset</b> is set to <code>0</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 1 through 10 from the list of items returned. If the <b>offset</b> is set to <code>10</code> and the <b>limit</b> is set to <code>10</code>, the method will retrieve items 11 through 20 from the list of items returned.<br /><br /><b>Valid Values:</b> <code>0-10,000</code><br /><br /><b>Default:</b> <code>0</code>
    *      - *prev* - string
    *          - The relative path to the previous set of results.
    *      - *total* - integer
    *          - The total number of matches for the search criteria.
    */
    public function batchCharityOrgs(array $query): Iterator
    {
        return $this->batchInternal('getCharityOrgs', func_get_args());
    }
        
}
