<?php

namespace lujie\amazon\advertising\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class DSPAdvertiserV3Const
{
        public const DSP_SUPPORTED_CURRENCY_V1_USD = 'USD';
        public const DSP_SUPPORTED_CURRENCY_V1_CAD = 'CAD';
        public const DSP_SUPPORTED_CURRENCY_V1_JPY = 'JPY';
        public const DSP_SUPPORTED_CURRENCY_V1_GBP = 'GBP';
        public const DSP_SUPPORTED_CURRENCY_V1_EUR = 'EUR';
        public const DSP_SUPPORTED_CURRENCY_V1_INR = 'INR';
        public const DSP_SUPPORTED_CURRENCY_V1_MXN = 'MXN';
        public const DSP_SUPPORTED_CURRENCY_V1_AED = 'AED';
        public const DSP_SUPPORTED_CURRENCY_V1_SAR = 'SAR';
        public const DSP_SUPPORTED_CURRENCY_V1_BRL = 'BRL';
        public const DSP_SUPPORTED_CURRENCY_V1_AUD = 'AUD';
        public const DSP_SUPPORTED_CURRENCY_V1_SEK = 'SEK';
        public const DSP_SUPPORTED_CURRENCY_V1_SGD = 'SGD';
        public const DSP_SUPPORTED_CURRENCY_V1_TRY = 'TRY';
        
        public const DSP_COUNTRY_V1_US = 'US';
        public const DSP_COUNTRY_V1_CA = 'CA';
        public const DSP_COUNTRY_V1_MX = 'MX';
        public const DSP_COUNTRY_V1_JP = 'JP';
        public const DSP_COUNTRY_V1_AU = 'AU';
        public const DSP_COUNTRY_V1_IN = 'IN';
        public const DSP_COUNTRY_V1_UK = 'UK';
        public const DSP_COUNTRY_V1_GB = 'GB';
        public const DSP_COUNTRY_V1_DE = 'DE';
        public const DSP_COUNTRY_V1_FR = 'FR';
        public const DSP_COUNTRY_V1_IT = 'IT';
        public const DSP_COUNTRY_V1_ES = 'ES';
        public const DSP_COUNTRY_V1_AT = 'AT';
        public const DSP_COUNTRY_V1_AE = 'AE';
        public const DSP_COUNTRY_V1_SA = 'SA';
        public const DSP_COUNTRY_V1_BR = 'BR';
        public const DSP_COUNTRY_V1_NL = 'NL';
        public const DSP_COUNTRY_V1_SE = 'SE';
        public const DSP_COUNTRY_V1_SG = 'SG';
        public const DSP_COUNTRY_V1_TR = 'TR';
        
}
