<?php

namespace lujie\amazon\sp\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
*/
class FulfillmentInbound20240320 extends \lujie\amazon\sp\BaseAmazonSPClient
{

                
    /**
     * @description Provides a list of inbound plans with minimal information.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of inbound plans to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     *      - *status* - string - optional
     *          - The status of an inbound plan.
     *      - *sortBy* - string - optional
     *          - Sort by field.
     *      - *sortOrder* - string - optional
     *          - The sort order.
     * @return array
     *      - *inboundPlans* - array
     *          - A list of inbound plans with minimal information.
     *      - *pagination* - 
     */
    public function listInboundPlans(array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans"], $query));
    }
                
    /**
     * @description Creates an inbound plan. An inbound plan contains all the necessary information to send shipments into Amazon's fufillment network.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $data 
     * @return array
     *      - *inboundPlanId* - string
     *          - Identifier of an inbound plan.
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function createInboundPlan(array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans", 'POST', $data);
    }
                    
    /**
     * @description Fetches the top level information about an inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @return array
     *      - *createdAt* - string
     *          - The time at which the inbound plan was created. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     *      - *inboundPlanId* - string
     *          - Identifier of an inbound plan.
     *      - *lastUpdatedAt* - string
     *          - The time at which the inbound plan was last updated. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ssZ`.
     *      - *marketplaceIds* - array
     *          - A list of marketplace IDs.
     *      - *name* - string
     *          - Human-readable name of the inbound plan.
     *      - *packingOptions* - array
     *          - Packing options for the inbound plan. This property will be populated when it has been generated via the corresponding operation. If there is a chosen placement option, only packing options for that placement option will be returned. If there are confirmed shipments, only packing options for those shipments will be returned. Query the packing option for more details.
     *      - *placementOptions* - array
     *          - Placement options for the inbound plan. This property will be populated when it has been generated via the corresponding operation. If there is a chosen placement option, that will be the only returned option. Query the placement option for more details.
     *      - *shipments* - array
     *          - A list of shipment IDs for the inbound plan. This property is populated when it has been generated with the `confirmPlacementOptions` operation. Only shipments from the chosen placement option are returned. Query the shipment for more details.
     *      - *sourceAddress* - 
     *      - *status* - string
     *          - Current status of the inbound plan. Possible values: `ACTIVE`, `VOIDED`, `SHIPPED`, `ERRORED`.
     */
    public function getInboundPlan(string $inboundPlanId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}");
    }
                    
    /**
     * @description Provides a paginated list of box packages in an inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of boxes to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *boxes* - array
     *          - A list of boxes in an inbound plan.
     *      - *pagination* - 
     */
    public function listInboundPlanBoxes(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/boxes"], $query));
    }
                    
    /**
     * @description Cancels an Inbound Plan. Charges may apply if the cancellation is performed outside of a void window. The window for Amazon Partnered Carriers is 24 hours for Small Parcel Delivery (SPD) and one hour for Less-Than-Truckload (LTL) carrier shipments.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function cancelInboundPlan(string $inboundPlanId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/cancellation", 'PUT');
    }
                    
    /**
     * @description Provides a paginated list of item packages in an inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of items to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *items* - array
     *          - The items in an inbound plan.
     *      - *pagination* - 
     */
    public function listInboundPlanItems(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/items"], $query));
    }
                    
    /**
     * @description Updates the name of an existing inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $data 
     */
    public function updateInboundPlanName(string $inboundPlanId, array $data): void
    {
        $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/name", 'PUT', $data);
    }
                    
    /**
     * @description Retrieves a page of boxes from a given packing group. These boxes were previously provided through the `setPackingInformation` operation. This API is used for workflows where boxes are packed before Amazon determines shipment splits.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $packingGroupId Identifier of a packing group.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of packing group boxes to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *boxes* - array
     *          - Provides the information about the list of boxes in the packing group.
     *      - *pagination* - 
     */
    public function listPackingGroupBoxes(string $inboundPlanId, string $packingGroupId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingGroups/{$packingGroupId}/boxes"], $query));
    }
                    
    /**
     * @description Retrieves a page of items in a given packing group. Packing options must first be generated by the corresponding operation before packing group items can be listed.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $packingGroupId Identifier of a packing group.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of packing group items to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *items* - array
     *          - Provides the information about the list of items in the packing group.
     *      - *pagination* - 
     */
    public function listPackingGroupItems(string $inboundPlanId, string $packingGroupId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingGroups/{$packingGroupId}/items"], $query));
    }
                    
    /**
     * @description Sets packing information for an inbound plan. This should be called after an inbound plan is created to populate the box level information required for planning and transportation estimates.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function setPackingInformation(string $inboundPlanId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingInformation", 'POST', $data);
    }
                    
    /**
     * @description Retrieves a list of all packing options for an inbound plan. Packing options must first be generated by the corresponding operation before becoming available.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of packing options to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *packingOptions* - array
     *          - List of packing options.
     *      - *pagination* - 
     */
    public function listPackingOptions(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingOptions"], $query));
    }
                
    /**
     * @description Generates available packing options for the inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generatePackingOptions(string $inboundPlanId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingOptions", 'POST');
    }
                    
    /**
     * @description Confirms the packing option for an inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $packingOptionId Identifier of a packing option.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function confirmPackingOption(string $inboundPlanId, string $packingOptionId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/packingOptions/{$packingOptionId}/confirmation", 'POST');
    }
                    
    /**
     * @description Provides a paginated list of pallet packages in an inbound plan. An inbound plan will have pallets when the related details are provided after generating Less-Than-Truckload (LTL) carrier shipments.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of pallets to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *pagination* - 
     *      - *pallets* - array
     *          - The pallets in an inbound plan.
     */
    public function listInboundPlanPallets(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/pallets"], $query));
    }
                    
    /**
     * @description Provides a list of all placement options for an inbound plan. Placement options must first be generated by the corresponding operation before becoming available.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of placement options to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *pagination* - 
     *      - *placementOptions* - array
     *          - Placement options generated for the inbound plan.
     */
    public function listPlacementOptions(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/placementOptions"], $query));
    }
                
    /**
     * @description Generates placement options for the inbound plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generatePlacementOptions(string $inboundPlanId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/placementOptions", 'POST', $data);
    }
                    
    /**
     * @description Confirms the placement option for an inbound plan. Once confirmed, it cannot be changed for the Inbound Plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $placementOptionId The identifier of a placement option. A placement option represents the shipment splits and destinations of SKUs.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function confirmPlacementOption(string $inboundPlanId, string $placementOptionId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/placementOptions/{$placementOptionId}/confirmation", 'POST');
    }
                    
    /**
     * @description Provides the full details for a specific shipment within an inbound plan. The `transportationOptionId` inside `acceptedTransportationSelection` can be used to retrieve the transportation details for the shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @return array
     *      - *amazonReferenceId* - string
     *          - A unique identifier created by Amazon that identifies this Amazon-partnered, Less Than Truckload/Full Truckload (LTL/FTL) shipment.
     *      - *contactInformation* - 
     *      - *dates* - 
     *      - *destination* - 
     *      - *freightInformation* - 
     *      - *name* - string
     *          - The name of the shipment.
     *      - *placementOptionId* - string
     *          - The identifier of a placement option. A placement option represents the shipment splits and destinations of SKUs.
     *      - *selectedDeliveryWindow* - 
     *      - *selectedTransportationOptionId* - string
     *          - Identifier of a transportation option. A transportation option represent one option for how to send a shipment.
     *      - *selfShipAppointmentDetails* - array
     *          - List of self ship appointment details.
     *      - *shipmentConfirmationId* - string
     *          - The confirmed shipment ID which shows up on labels (for example, `FBA1234ABCD`).
     *      - *shipmentId* - string
     *          - Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     *      - *source* - 
     *      - *status* - string
     *          - The status of a shipment. The state of the shipment will typically start as `UNCONFIRMED`, then transition to `WORKING` after a placement option has been confirmed, and then to `READY_TO_SHIP` once labels are generated.

Possible values: `ABANDONED`, `CANCELLED`, `CHECKED_IN`, `CLOSED`, `DELETED`, `DELIVERED`, `IN_TRANSIT`, `MIXED`, `READY_TO_SHIP`, `RECEIVING`, `SHIPPED`, `UNCONFIRMED`, `WORKING`
     *      - *trackingDetails* - 
     */
    public function getShipment(string $inboundPlanId, string $shipmentId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}");
    }
                    
    /**
     * @description Provides a paginated list of box packages in a shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of boxes to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *boxes* - array
     *          - A list of boxes in a shipment.
     *      - *pagination* - 
     */
    public function listShipmentBoxes(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/boxes"], $query));
    }
                    
    /**
     * @description Retrieve a paginated list of shipment content update previews for a given shipment. The shipment content update preview is a summary of the requested shipment content changes along with the transportation cost implications of the change that can only be confirmed prior to the expiry date specified.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of content update previews to return.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *contentUpdatePreviews* - array
     *          - A list of content update previews in a shipment.
     *      - *pagination* - 
     */
    public function listShipmentContentUpdatePreviews(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/contentUpdatePreviews"], $query));
    }
                
    /**
     * @description Generate a shipment content update preview given a set of intended boxes and/or items for a shipment with a confirmed carrier. The shipment content update preview will be viewable with the updated costs and contents prior to confirmation.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generateShipmentContentUpdatePreviews(string $inboundPlanId, string $shipmentId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/contentUpdatePreviews", 'POST', $data);
    }
                    
    /**
     * @description Retrieve a shipment content update preview which provides a summary of the requested shipment content changes along with the transportation cost implications of the change that can only be confirmed prior to the expiry date specified.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param string $contentUpdatePreviewId Identifier of a content update preview.
     * @return array
     *      - *contentUpdatePreviewId* - string
     *          - Identifier of a content update preview.
     *      - *expiration* - string
     *          - The time at which the content update expires. In [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) datetime format with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
     *      - *requestedUpdates* - 
     *      - *transportationOption* - 
     */
    public function getShipmentContentUpdatePreview(string $inboundPlanId, string $shipmentId, string $contentUpdatePreviewId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/contentUpdatePreviews/{$contentUpdatePreviewId}");
    }
                    
    /**
     * @description Confirm a shipment content update preview and accept the changes in transportation cost.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param string $contentUpdatePreviewId Identifier of a content update preview.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function confirmShipmentContentUpdatePreview(string $inboundPlanId, string $shipmentId, string $contentUpdatePreviewId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/contentUpdatePreviews/{$contentUpdatePreviewId}/confirmation", 'POST');
    }
                    
    /**
     * @description Provide delivery challan document for PCP transportation in IN marketplace.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @return array
     *      - *documentDownload* - 
     */
    public function getDeliveryChallanDocument(string $inboundPlanId, string $shipmentId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/deliveryChallanDocument");
    }
                    
    /**
     * @description Retrieves all delivery window options for a shipment. Delivery window options must first be generated by the `generateDeliveryWindowOptions` operation before becoming available.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId The shipment to get delivery window options for.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of delivery window options to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *deliveryWindowOptions* - array
     *          - Delivery window options generated for the placement option.
     *      - *pagination* - 
     */
    public function listDeliveryWindowOptions(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/deliveryWindowOptions"], $query));
    }
                
    /**
     * @description Generates available delivery window options for a given shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId The shipment to generate delivery window options for.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generateDeliveryWindowOptions(string $inboundPlanId, string $shipmentId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/deliveryWindowOptions", 'POST');
    }
                    
    /**
     * @description Confirms the delivery window option for chosen shipment within an inbound plan. A placement option must be confirmed prior to use of this API. Once confirmed, new delivery window options cannot be generated, but the chosen delivery window option can be updated before shipment closure. The window is used to provide the expected time when a shipment will arrive at the warehouse. All transportation options which have the program `CONFIRMED_DELIVERY_WINDOW` require a delivery window to be confirmed prior to transportation option confirmation.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId The shipment to confirm the delivery window option for.
     * @param string $deliveryWindowOptionId The id of the delivery window option to be confirmed.
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function confirmDeliveryWindowOptions(string $inboundPlanId, string $shipmentId, string $deliveryWindowOptionId): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/deliveryWindowOptions/{$deliveryWindowOptionId}/confirmation", 'POST');
    }
                    
    /**
     * @description Provides a paginated list of item packages in a shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of items to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *items* - array
     *          - The items in a shipment.
     *      - *pagination* - 
     */
    public function listShipmentItems(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/items"], $query));
    }
                    
    /**
     * @description Updates the name of an existing shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     */
    public function updateShipmentName(string $inboundPlanId, string $shipmentId, array $data): void
    {
        $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/name", 'PUT', $data);
    }
                    
    /**
     * @description Provides a paginated list of pallet packages in a shipment. A palletized shipment will have pallets when the related details are provided after generating Less-Than-Truckload (LTL) carrier shipments.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of pallets to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *pagination* - 
     *      - *pallets* - array
     *          - The pallets in a shipment.
     */
    public function listShipmentPallets(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/pallets"], $query));
    }
                    
    /**
     * @description Cancels a self-ship appointment slot against a shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function cancelSelfShipAppointment(string $inboundPlanId, string $shipmentId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/selfShipAppointmentCancellation", 'PUT', $data);
    }
                    
    /**
     * @description Retrieves a list of available self-ship appointment slots used to drop off a shipment at a warehouse.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of self ship appointment slots to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     * @return array
     *      - *pagination* - 
     *      - *selfShipAppointmentSlotsAvailability* - 
     */
    public function getSelfShipAppointmentSlots(string $inboundPlanId, string $shipmentId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/selfShipAppointmentSlots"], $query));
    }
                
    /**
     * @description Initiates the process of generating the appointment slots list.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generateSelfShipAppointmentSlots(string $inboundPlanId, string $shipmentId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/selfShipAppointmentSlots", 'POST', $data);
    }
                    
    /**
     * @description Confirms or reschedules a self-ship appointment slot against a shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param string $slotId An identifier to a self-ship appointment slot.
     * @param array $data 
     * @return array
     *      - *selfShipAppointmentDetails* - 
     */
    public function scheduleSelfShipAppointment(string $inboundPlanId, string $shipmentId, string $slotId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/selfShipAppointmentSlots/{$slotId}/schedule", 'POST', $data);
    }
                    
    /**
     * @description Updates the source address of an existing shipment. The shipment source address can only be updated prior to the confirmation of the shipment carriers. As a result of the updated source address, existing transportation options will be invalidated and will need to be regenerated to capture the potential difference in transportation options and quotes due to the new source address.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function updateShipmentSourceAddress(string $inboundPlanId, string $shipmentId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/sourceAddress", 'PUT', $data);
    }
                    
    /**
     * @description Updates a shipment's tracking details.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param string $shipmentId Identifier of a shipment. A shipment contains the boxes and units being inbounded.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function updateShipmentTrackingDetails(string $inboundPlanId, string $shipmentId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/shipments/{$shipmentId}/trackingDetails", 'PUT', $data);
    }
                    
    /**
     * @description Retrieves all transportation options for a shipment. Transportation options must first be generated by the `generateTransportationOptions` operation before becoming available.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $query
     *      - *pageSize* - integer - optional
     *          - The number of transportation options to return in the response matching the given query.
     *      - *paginationToken* - string - optional
     *          - A token to fetch a certain page when there are multiple pages worth of results. The value of this token is fetched from the `pagination` returned in the API response. In the absence of the token value from the query parameter the API returns the first page of the result.
     *      - *placementOptionId* - string - optional
     *          - The placement option to get transportation options for. Either `placementOptionId` or `shipmentId` must be specified.
     *      - *shipmentId* - string - optional
     *          - The shipment to get transportation options for. Either `placementOptionId` or `shipmentId` must be specified.
     * @return array
     *      - *pagination* - 
     *      - *transportationOptions* - array
     *          - Transportation options generated for the placement option.
     */
    public function listTransportationOptions(string $inboundPlanId, array $query = []): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/transportationOptions"], $query));
    }
                
    /**
     * @description Generates available transportation options for a given placement option.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function generateTransportationOptions(string $inboundPlanId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/transportationOptions", 'POST', $data);
    }
                    
    /**
     * @description Confirms all the transportation options for an inbound plan. A placement option must be confirmed prior to use of this API. Once confirmed, new transportation options can not be generated or confirmed for the Inbound Plan.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 2 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $inboundPlanId Identifier of an inbound plan.
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function confirmTransportationOptions(string $inboundPlanId, array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/inboundPlans/{$inboundPlanId}/transportationOptions/confirmation", 'POST', $data);
    }
                    
    /**
     * @description List the inbound compliance details for MSKUs in a given marketplace.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $query
     *      - *mskus* - array - required
     *          - A list of merchant SKUs, a merchant-supplied identifier of a specific SKU.
     *      - *marketplaceId* - string - required
     *          - The Marketplace ID. For a list of possible values, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
     * @return array
     *      - *complianceDetails* - array
     *          - List of compliance details.
     */
    public function listItemComplianceDetails(array $query): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/items/compliance"], $query));
    }
                
    /**
     * @description Update compliance details for a list of MSKUs. The details provided here are only used for the India (IN - A21TJRUUN4KGV) marketplace compliance validation.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The Marketplace ID. For a list of possible values, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function updateItemComplianceDetails(array $query, array $data): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/items/compliance"], $query), 'PUT', $data);
    }
                    
    /**
     * @description For a given marketplace - creates labels for a list of MSKUs.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $data 
     * @return array
     *      - *documentDownloads* - array
     *          - Resources to download the requested document.
     */
    public function createMarketplaceItemLabels(array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/items/labels", 'POST', $data);
    }
                    
    /**
     * @description Get preparation details for a list of MSKUs in a specified marketplace.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $query
     *      - *marketplaceId* - string - required
     *          - The marketplace ID. For a list of possible values, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
     *      - *mskus* - array - required
     *          - A list of merchant SKUs, a merchant-supplied identifier of a specific SKU.
     * @return array
     *      - *mskuPrepDetails* - array
     *          - A list of MSKUs and related prep details.
     */
    public function listPrepDetails(array $query): array
    {
        return $this->api(array_merge(["/inbound/fba/2024-03-20/items/prepDetails"], $query));
    }
                
    /**
     * @description Set the preparation details for a list of MSKUs in a specified marketplace.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param array $data 
     * @return array
     *      - *operationId* - string
     *          - UUID for the given operation.
     */
    public function setPrepDetails(array $data): array
    {
        return $this->api("/inbound/fba/2024-03-20/items/prepDetails", 'POST', $data);
    }
                    
    /**
     * @description Gets the status of the processing of an asynchronous API call.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 6 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The preceding table contains the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may have higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag Fulfillment Inbound
     * @param string $operationId Identifier of an asynchronous operation.
     * @return array
     *      - *operation* - string
     *          - The name of the operation in the asynchronous API call.
     *      - *operationId* - string
     *          - The operation ID returned by the asynchronous API call.
     *      - *operationProblems* - array
     *          - The problems in the processing of the asynchronous operation.
     *      - *operationStatus* - 
     */
    public function getInboundOperationStatus(string $operationId): array
    {
        return $this->api("/inbound/fba/2024-03-20/operations/{$operationId}");
    }
    
}
