<?php

namespace lujie\amazon\sp\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class ListingsItems20200901Const
{
        public const ISSUE_SEVERITY_ERROR = 'ERROR';
        public const ISSUE_SEVERITY_WARNING = 'WARNING';
        public const ISSUE_SEVERITY_INFO = 'INFO';
        
        public const PATCH_OPERATION_OP_ADD = 'add';
        public const PATCH_OPERATION_OP_REPLACE = 'replace';
        public const PATCH_OPERATION_OP_DELETE = 'delete';
        
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING = 'LISTING';
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING_PRODUCT_ONLY = 'LISTING_PRODUCT_ONLY';
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING_OFFER_ONLY = 'LISTING_OFFER_ONLY';
        
        public const LISTINGS_ITEM_SUBMISSION_RESPONSE_STATUS_ACCEPTED = 'ACCEPTED';
        public const LISTINGS_ITEM_SUBMISSION_RESPONSE_STATUS_INVALID = 'INVALID';
        
}
