<?php

namespace lujie\amazon\sp\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class ListingsItems20210801Const
{
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_NEW_NEW = 'new_new';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_NEW_OPEN_BOX = 'new_open_box';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_NEW_OEM = 'new_oem';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_REFURBISHED_REFURBISHED = 'refurbished_refurbished';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_USED_LIKE_NEW = 'used_like_new';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_USED_VERY_GOOD = 'used_very_good';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_USED_GOOD = 'used_good';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_USED_ACCEPTABLE = 'used_acceptable';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_COLLECTIBLE_LIKE_NEW = 'collectible_like_new';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_COLLECTIBLE_VERY_GOOD = 'collectible_very_good';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_COLLECTIBLE_GOOD = 'collectible_good';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_COLLECTIBLE_ACCEPTABLE = 'collectible_acceptable';
        public const ITEM_SUMMARY_BY_MARKETPLACE_CONDITION_TYPE_CLUB_CLUB = 'club_club';
        
        public const ISSUE_SEVERITY_ERROR = 'ERROR';
        public const ISSUE_SEVERITY_WARNING = 'WARNING';
        public const ISSUE_SEVERITY_INFO = 'INFO';
        
        public const ITEM_OFFER_BY_MARKETPLACE_OFFER_TYPE_B2C = 'B2C';
        public const ITEM_OFFER_BY_MARKETPLACE_OFFER_TYPE_B2B = 'B2B';
        
        public const PATCH_OPERATION_OP_ADD = 'add';
        public const PATCH_OPERATION_OP_REPLACE = 'replace';
        public const PATCH_OPERATION_OP_DELETE = 'delete';
        
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING = 'LISTING';
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING_PRODUCT_ONLY = 'LISTING_PRODUCT_ONLY';
        public const LISTINGS_ITEM_PUT_REQUEST_REQUIREMENTS_LISTING_OFFER_ONLY = 'LISTING_OFFER_ONLY';
        
        public const LISTINGS_ITEM_SUBMISSION_RESPONSE_STATUS_ACCEPTED = 'ACCEPTED';
        public const LISTINGS_ITEM_SUBMISSION_RESPONSE_STATUS_INVALID = 'INVALID';
        
}
