<?php

namespace lujie\amazon\sp\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
*/
class MerchantFulfillmentV0 extends \lujie\amazon\sp\BaseAmazonSPClient
{

                
    /**
     * @description Returns a list of shipping service offers that satisfy the specified shipment request details.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param array $data 
     * @return array
     *      - *payload* - 
     *      - *errors* - 
     *          - One or more unexpected errors occurred during this operation.
     */
    public function getEligibleShipmentServicesOld(array $data): array
    {
        return $this->api("/mfn/v0/eligibleServices", 'POST', $data);
    }
                    
    /**
     * @description Returns a list of shipping service offers that satisfy the specified shipment request details.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 5 | 10 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param array $data 
     * @return array
     *      - *payload* - 
     *      - *errors* - 
     *          - One or more unexpected errors occurred during this operation.
     */
    public function getEligibleShipmentServices(array $data): array
    {
        return $this->api("/mfn/v0/eligibleShippingServices", 'POST', $data);
    }
                    
    /**
     * @description Returns the shipment information for an existing shipment.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param string $shipmentId The Amazon-defined shipment identifier for the shipment.
     * @return array
     *      - *payload* - 
     *          - The payload for the getShipment operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during this operation.
     */
    public function getShipment(string $shipmentId): array
    {
        return $this->api("/mfn/v0/shipments/{$shipmentId}");
    }
                
    /**
     * @description Cancel the shipment indicated by the specified shipment identifier.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param string $shipmentId The Amazon-defined shipment identifier for the shipment to cancel.
     * @return array
     *      - *payload* - 
     *          - The payload for the cancelShipment operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the cancelShipment operation.
     */
    public function cancelShipment(string $shipmentId): array
    {
        return $this->api("/mfn/v0/shipments/{$shipmentId}", 'DELETE');
    }
                    
    /**
     * @description Cancel the shipment indicated by the specified shipment identifer.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param string $shipmentId The Amazon-defined shipment identifier for the shipment to cancel.
     * @return array
     *      - *payload* - 
     *          - The payload for the cancelShipment operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the cancelShipment operation.
     */
    public function cancelShipmentOld(string $shipmentId): array
    {
        return $this->api("/mfn/v0/shipments/{$shipmentId}/cancel", 'PUT');
    }
                    
    /**
     * @description Create a shipment with the information provided.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param array $data 
     * @return array
     *      - *payload* - 
     *          - Shipment information.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the createShipment operation.
     */
    public function createShipment(array $data): array
    {
        return $this->api("/mfn/v0/shipments", 'POST', $data);
    }
                    
    /**
     * @description Get a list of additional seller inputs required for a ship method. This is generally used for international shipping.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param array $data 
     * @return array
     *      - *payload* - 
     *      - *errors* - 
     */
    public function getAdditionalSellerInputsOld(array $data): array
    {
        return $this->api("/mfn/v0/sellerInputs", 'POST', $data);
    }
                    
    /**
     * @description Gets a list of additional seller inputs required for a ship method. This is generally used for international shipping.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 1 | 1 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag merchantFulfillment
     * @param array $data 
     * @return array
     *      - *payload* - 
     *      - *errors* - 
     */
    public function getAdditionalSellerInputs(array $data): array
    {
        return $this->api("/mfn/v0/additionalSellerInputs", 'POST', $data);
    }
    
}
