<?php

namespace lujie\plentyMarkets\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The plentymarkets REST API expands the functionality of the plentymarkets CMS and allows access to resources, i.e. data records, via unique URI paths
*/
class OrderSummary extends \lujie\plentyMarkets\BasePlentyMarketsRestClient
{

                
    /**
     * @description Lists order summaries.
     * @tag OrderSummary
     * @return array
     */
    public function getAccountsOrderSummaries(): array
    {
        return $this->api("/rest/accounts/order_summaries");
    }
                
    /**
     * @description Creates an order summary.
     * @tag OrderSummary
     * @return array
     *      - *id* - integer
     *          - The ID of the order summary
     *      - *addressId* - integer
     *          - The address ID of the order summary
     *      - *contactId* - integer
     *          - The ID of the contact
     *      - *unpaidOrdersCount* - integer
     *          - The number of unpaid orders
     *      - *unpaidOrderTotalAmount* - number
     *          - The total amount of unpaid orders
     *      - *orderCount* - integer
     *          - The number of all orders of the associated model
     *      - *createdAt* - string
     *          - The time the order summary was created as unix timestamp
     *      - *updatedAt* - string
     *          - The time the order summary was last updated as unix timestamp
     */
    public function createAccountsOrderSummary(): array
    {
        return $this->api("/rest/accounts/order_summaries", 'POST');
    }
                    
    /**
     * @description Gets an order summary. The ID of the contact must be specified.
     * @tag OrderSummary
     * @param int $contactId 
     * @return array
     *      - *id* - integer
     *          - The ID of the order summary
     *      - *addressId* - integer
     *          - The address ID of the order summary
     *      - *contactId* - integer
     *          - The ID of the contact
     *      - *unpaidOrdersCount* - integer
     *          - The number of unpaid orders
     *      - *unpaidOrderTotalAmount* - number
     *          - The total amount of unpaid orders
     *      - *orderCount* - integer
     *          - The number of all orders of the associated model
     *      - *createdAt* - string
     *          - The time the order summary was created as unix timestamp
     *      - *updatedAt* - string
     *          - The time the order summary was last updated as unix timestamp
     */
    public function getAccountsOrderSummariesContactByContactId(int $contactId): array
    {
        return $this->api("/rest/accounts/order_summaries/contacts/{$contactId}");
    }
                    
    /**
     * @description Gets an order summary. The ID of the address must be specified.
     * @tag OrderSummary
     * @param int $addressId 
     * @return array
     *      - *id* - integer
     *          - The ID of the order summary
     *      - *addressId* - integer
     *          - The address ID of the order summary
     *      - *contactId* - integer
     *          - The ID of the contact
     *      - *unpaidOrdersCount* - integer
     *          - The number of unpaid orders
     *      - *unpaidOrderTotalAmount* - number
     *          - The total amount of unpaid orders
     *      - *orderCount* - integer
     *          - The number of all orders of the associated model
     *      - *createdAt* - string
     *          - The time the order summary was created as unix timestamp
     *      - *updatedAt* - string
     *          - The time the order summary was last updated as unix timestamp
     */
    public function getAccountsOrderSummariesOrderByAddressId(int $addressId): array
    {
        return $this->api("/rest/accounts/order_summaries/orders/{$addressId}");
    }
                    
    /**
     * @description Get all unpaid order summaries.
     * @tag OrderSummary
     * @return array
     *      - *page* - integer
     *          - Current page of the response
     *      - *totalsCount* - integer
     *          - The total number of entries in the response
     *      - *isLastPage* - boolean
     *          - Flag that indicates if the page shown is the last page of the response
     *      - *lastPageNumber* - integer
     *          - The last page number
     *      - *firstOnPage* - integer
     *          - The index of the first item of the current page result
     *      - *lastOnPage* - integer
     *          - The index of the last item of the current page result
     *      - *itemsPerPage* - integer
     *          - The requested amount of items per result page
     *      - *entries* - array
     *          - List of OrderSummary
     */
    public function getAccountsOrderSummariesUnpaid(): array
    {
        return $this->api("/rest/accounts/order_summaries/unpaid");
    }
                    
    /**
     * @description Deletes an order summary. The ID of the order summary must be specified.
     * @tag OrderSummary
     * @param int $orderSummaryId 
     */
    public function deleteAccountsOrderSummaryByOrderSummaryId(int $orderSummaryId): void
    {
        $this->api("/rest/accounts/order_summaries/{$orderSummaryId}", 'DELETE');
    }
                
    /**
     * @description Gets an order summary. The ID of the order summary must be specified.
     * @tag OrderSummary
     * @param int $orderSummaryId 
     * @return array
     *      - *id* - integer
     *          - The ID of the order summary
     *      - *addressId* - integer
     *          - The address ID of the order summary
     *      - *contactId* - integer
     *          - The ID of the contact
     *      - *unpaidOrdersCount* - integer
     *          - The number of unpaid orders
     *      - *unpaidOrderTotalAmount* - number
     *          - The total amount of unpaid orders
     *      - *orderCount* - integer
     *          - The number of all orders of the associated model
     *      - *createdAt* - string
     *          - The time the order summary was created as unix timestamp
     *      - *updatedAt* - string
     *          - The time the order summary was last updated as unix timestamp
     */
    public function getAccountsOrderSummaryByOrderSummaryId(int $orderSummaryId): array
    {
        return $this->api("/rest/accounts/order_summaries/{$orderSummaryId}");
    }
                
    /**
     * @description Updates an order summary. The ID of the order summary must be specified.
     * @tag OrderSummary
     * @param int $orderSummaryId 
     * @return array
     *      - *id* - integer
     *          - The ID of the order summary
     *      - *addressId* - integer
     *          - The address ID of the order summary
     *      - *contactId* - integer
     *          - The ID of the contact
     *      - *unpaidOrdersCount* - integer
     *          - The number of unpaid orders
     *      - *unpaidOrderTotalAmount* - number
     *          - The total amount of unpaid orders
     *      - *orderCount* - integer
     *          - The number of all orders of the associated model
     *      - *createdAt* - string
     *          - The time the order summary was created as unix timestamp
     *      - *updatedAt* - string
     *          - The time the order summary was last updated as unix timestamp
     */
    public function updateAccountsOrderSummaryByOrderSummaryId(int $orderSummaryId): array
    {
        return $this->api("/rest/accounts/order_summaries/{$orderSummaryId}", 'PUT');
    }
    
}
