<?php

namespace lujie\amazon\sp\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools. The Orders API only supports orders that are less than two years old. Orders more than two years old will not show in the API response.
*/
class OrdersV0 extends \lujie\amazon\sp\BaseAmazonSPClient
{

                
    /**
     * @description Returns orders created or updated during the time frame indicated by the specified parameters. You can also apply a range of filtering criteria to narrow the list of orders returned. If NextToken is present, that will be used to retrieve the orders instead of other criteria.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.0167 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param array $query
     *      - *CreatedAfter* - string - optional
     *          - A date used for selecting orders created after (or at) a specified time. Only orders placed after the specified time are returned. Either the CreatedAfter parameter or the LastUpdatedAfter parameter is required. Both cannot be empty. The date must be in ISO 8601 format.
     *      - *CreatedBefore* - string - optional
     *          - A date used for selecting orders created before (or at) a specified time. Only orders placed before the specified time are returned. The date must be in ISO 8601 format.
     *      - *LastUpdatedAfter* - string - optional
     *          - A date used for selecting orders that were last updated after (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
     *      - *LastUpdatedBefore* - string - optional
     *          - A date used for selecting orders that were last updated before (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
     *      - *OrderStatuses* - array - optional
     *          - A list of `OrderStatus` values used to filter the results.

**Possible values:**
- `PendingAvailability` (This status is available for pre-orders only. The order has been placed, payment has not been authorized, and the release date of the item is in the future.)
- `Pending` (The order has been placed but payment has not been authorized.)
- `Unshipped` (Payment has been authorized and the order is ready for shipment, but no items in the order have been shipped.)
- `PartiallyShipped` (One or more, but not all, items in the order have been shipped.)
- `Shipped` (All items in the order have been shipped.)
- `InvoiceUnconfirmed` (All items in the order have been shipped. The seller has not yet given confirmation to Amazon that the invoice has been shipped to the buyer.)
- `Canceled` (The order has been canceled.)
- `Unfulfillable` (The order cannot be fulfilled. This state applies only to Multi-Channel Fulfillment orders.)
     *      - *MarketplaceIds* - array - required
     *          - A list of MarketplaceId values. Used to select orders that were placed in the specified marketplaces.

See the [Selling Partner API Developer Guide](doc:marketplace-ids) for a complete list of marketplaceId values.
     *      - *FulfillmentChannels* - array - optional
     *          - A list that indicates how an order was fulfilled. Filters the results by fulfillment channel. Possible values: AFN (Fulfillment by Amazon); MFN (Fulfilled by the seller).
     *      - *PaymentMethods* - array - optional
     *          - A list of payment method values. Used to select orders paid using the specified payment methods. Possible values: COD (Cash on delivery); CVS (Convenience store payment); Other (Any payment method other than COD or CVS).
     *      - *BuyerEmail* - string - optional
     *          - The email address of a buyer. Used to select orders that contain the specified email address.
     *      - *SellerOrderId* - string - optional
     *          - An order identifier that is specified by the seller. Used to select only the orders that match the order identifier. If SellerOrderId is specified, then FulfillmentChannels, OrderStatuses, PaymentMethod, LastUpdatedAfter, LastUpdatedBefore, and BuyerEmail cannot be specified.
     *      - *MaxResultsPerPage* - integer - optional
     *          - A number that indicates the maximum number of orders that can be returned per page. Value must be 1 - 100. Default 100.
     *      - *EasyShipShipmentStatuses* - array - optional
     *          - A list of `EasyShipShipmentStatus` values. Used to select Easy Ship orders with statuses that match the specified values. If `EasyShipShipmentStatus` is specified, only Amazon Easy Ship orders are returned.

**Possible values:**
- `PendingSchedule` (The package is awaiting the schedule for pick-up.)
- `PendingPickUp` (Amazon has not yet picked up the package from the seller.)
- `PendingDropOff` (The seller will deliver the package to the carrier.)
- `LabelCanceled` (The seller canceled the pickup.)
- `PickedUp` (Amazon has picked up the package from the seller.)
- `DroppedOff` (The package is delivered to the carrier by the seller.)
- `AtOriginFC` (The packaged is at the origin fulfillment center.)
- `AtDestinationFC` (The package is at the destination fulfillment center.)
- `Delivered` (The package has been delivered.)
- `RejectedByBuyer` (The package has been rejected by the buyer.)
- `Undeliverable` (The package cannot be delivered.)
- `ReturningToSeller` (The package was not delivered and is being returned to the seller.)
- `ReturnedToSeller` (The package was not delivered and was returned to the seller.)
- `Lost` (The package is lost.)
- `OutForDelivery` (The package is out for delivery.)
- `Damaged` (The package was damaged by the carrier.)
     *      - *ElectronicInvoiceStatuses* - array - optional
     *          - A list of `ElectronicInvoiceStatus` values. Used to select orders with electronic invoice statuses that match the specified values.

**Possible values:**
- `NotRequired` (Electronic invoice submission is not required for this order.)
- `NotFound` (The electronic invoice was not submitted for this order.)
- `Processing` (The electronic invoice is being processed for this order.)
- `Errored` (The last submitted electronic invoice was rejected for this order.)
- `Accepted` (The last submitted electronic invoice was submitted and accepted.)
     *      - *NextToken* - string - optional
     *          - A string token returned in the response of your previous request.
     *      - *AmazonOrderIds* - array - optional
     *          - A list of AmazonOrderId values. An AmazonOrderId is an Amazon-defined order identifier, in 3-7-7 format.
     *      - *ActualFulfillmentSupplySourceId* - string - optional
     *          - Denotes the recommended sourceId where the order should be fulfilled from.
     *      - *IsISPU* - boolean - optional
     *          - When true, this order is marked to be picked up from a store rather than delivered.
     *      - *StoreChainStoreId* - string - optional
     *          - The store chain store identifier. Linked to a specific store in a store chain.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrders operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrders operation.
     */
    public function getOrders(array $query): array
    {
        return $this->api(array_merge(["/orders/v0/orders"], $query));
    }
                    
    /**
     * @description Returns the order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.0167 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An Amazon-defined order identifier, in 3-7-7 format.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrder operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrder operation.
     */
    public function getOrder(string $orderId): array
    {
        return $this->api("/orders/v0/orders/{$orderId}");
    }
                    
    /**
     * @description Returns buyer information for the order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.0167 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An orderId is an Amazon-defined order identifier, in 3-7-7 format.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrderBuyerInfo operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrderBuyerInfo operation.
     */
    public function getOrderBuyerInfo(string $orderId): array
    {
        return $this->api("/orders/v0/orders/{$orderId}/buyerInfo");
    }
                    
    /**
     * @description Returns the shipping address for the order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.0167 | 20 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An orderId is an Amazon-defined order identifier, in 3-7-7 format.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrderAddress operations.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrderAddress operation.
     */
    public function getOrderAddress(string $orderId): array
    {
        return $this->api("/orders/v0/orders/{$orderId}/address");
    }
                    
    /**
     * @description Returns detailed order item information for the order that you specify. If NextToken is provided, it's used to retrieve the next page of order items.

__Note__: When an order is in the Pending state (the order has been placed but payment has not been authorized), the getOrderItems operation does not return information about pricing, taxes, shipping charges, gift status or promotions for the order items in the order. After an order leaves the Pending state (this occurs when payment has been authorized) and enters the Unshipped, Partially Shipped, or Shipped state, the getOrderItems operation returns information about pricing, taxes, shipping charges, gift status and promotions for the order items in the order.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.5 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An Amazon-defined order identifier, in 3-7-7 format.
     * @param array $query
     *      - *NextToken* - string - optional
     *          - A string token returned in the response of your previous request.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrderItems operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrderItems operation.
     */
    public function getOrderItems(string $orderId, array $query = []): array
    {
        return $this->api(array_merge(["/orders/v0/orders/{$orderId}/orderItems"], $query));
    }
                    
    /**
     * @description Returns buyer information for the order items in the order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.5 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An Amazon-defined order identifier, in 3-7-7 format.
     * @param array $query
     *      - *NextToken* - string - optional
     *          - A string token returned in the response of your previous request.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrderItemsBuyerInfo operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrderItemsBuyerInfo operation.
     */
    public function getOrderItemsBuyerInfo(string $orderId, array $query = []): array
    {
        return $this->api(array_merge(["/orders/v0/orders/{$orderId}/orderItems/buyerInfo"], $query));
    }
                    
    /**
     * @description Update the shipment status for an order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 5 | 15 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag shipment
     * @param string $orderId An Amazon-defined order identifier, in 3-7-7 format.
     * @param array $data 
     */
    public function updateShipmentStatus(string $orderId, array $data): void
    {
        $this->api("/orders/v0/orders/{$orderId}/shipment", 'POST', $data);
    }
                    
    /**
     * @description Returns regulated information for the order that you specify.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.5 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An orderId is an Amazon-defined order identifier, in 3-7-7 format.
     * @return array
     *      - *payload* - 
     *          - The payload for the getOrderRegulatedInfo operation.
     *      - *errors* - 
     *          - One or more unexpected errors occurred during the getOrderRegulatedInfo operation.
     */
    public function getOrderRegulatedInfo(string $orderId): array
    {
        return $this->api("/orders/v0/orders/{$orderId}/regulatedInfo");
    }
                
    /**
     * @description Updates (approves or rejects) the verification status of an order containing regulated products.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 0.5 | 30 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An orderId is an Amazon-defined order identifier, in 3-7-7 format.
     * @param array $data 
     */
    public function updateVerificationStatus(string $orderId, array $data): void
    {
        $this->api("/orders/v0/orders/{$orderId}/regulatedInfo", 'PATCH', $data);
    }
                    
    /**
     * @description Updates the shipment confirmation status for a specified order.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 2 | 10 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
     * @tag ordersV0
     * @param string $orderId An Amazon-defined order identifier, in 3-7-7 format.
     * @param array $data 
     */
    public function confirmShipment(string $orderId, array $data): void
    {
        $this->api("/orders/v0/orders/{$orderId}/shipmentConfirmation", 'POST', $data);
    }
    
}
