<?php

namespace lujie\amazon\advertising\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class PortfoliosV2Const
{
        public const PORTFOLIO_STATE_ENABLED = 'enabled';
        
}
