<?php

namespace lujie\amazon\sp\api;

/**
* This class is autogenerated by the OpenAPI gii generator
*/
class VendorDirectFulfillmentSandboxData20211028Const
{
        public const TRANSACTION_STATUS_FAILURE = 'FAILURE';
        public const TRANSACTION_STATUS_PROCESSING = 'PROCESSING';
        public const TRANSACTION_STATUS_SUCCESS = 'SUCCESS';
        
}
