<?php

namespace lujie\amazon\sp\api;

use Yii;
use Iterator;

/**
* This class is autogenerated by the OpenAPI gii generator
* @description The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
*/
class VendorDirectFulfillmentInventoryV1 extends \lujie\amazon\sp\BaseAmazonSPClient
{

                
    /**
     * @description Submits inventory updates for the specified warehouse for either a partial or full feed of inventory items.

**Usage Plan:**

| Rate (requests per second) | Burst |
| ---- | ---- |
| 10 | 10 |

The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that are applied to the operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, refer to [Usage Plans and Rate Limits in the *SP-API*](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @tag updateInventory
     * @param string $warehouseId Identifier for the warehouse for which to update inventory.
     * @param array $data 
     * @return array
     *      - *payload* - 
     *          - The response payload for the `submitInventoryUpdate` operation.
     *      - *errors* - 
     */
    public function submitInventoryUpdate(string $warehouseId, array $data): array
    {
        return $this->api("/vendor/directFulfillment/inventory/v1/warehouses/{$warehouseId}/items", 'POST', $data);
    }
        
}
