<?php
/**
 * @copyright Copyright (c) 2019
 */

namespace lujie\amazon\sp;

/**
 * Class AmazonSPConst
 * @package lujie\amazon\sp
 * @author Lujie Zhou <gao_lujie@live.cn>
 */
class AmazonSPConst
{
    public const API_URL_NA = 'https://sellingpartnerapi-na.amazon.com';
    public const API_URL_EU = 'https://sellingpartnerapi-eu.amazon.com';
    public const API_URL_FE = 'https://sellingpartnerapi-fe.amazon.com';

    public const AUTH_URL_US = 'https://sellercentral.amazon.com/apps/authorize/consent';
    public const AUTH_URL_EU = 'https://sellercentral-europe.amazon.com/apps/authorize/consent';

    public const TOKEN_URL = 'https://api.amazon.com/auth/o2/token';

    public const REGION_US_EAST_1 = 'us-east-1';
    public const REGION_EU_WEST_1 = 'eu-west-1';
    public const REGION_US_WEST_2 = 'us-west-2';

    public const HOST_US_EAST_1 = 'sellingpartnerapi-na.amazon.com';
    public const HOST_US_WEST_2 = 'sellingpartnerapi-fe.amazon.com';
    public const HOST_EU_WEST_1 = 'sellingpartnerapi-eu.amazon.com';

    public const MARKETPLACES = [
        'CA' => 'A2EUQ1WTGCTBG2',
        'US' => 'ATVPDKIKX0DER',
        'MX' => 'A1AM78C64UM0Y8',
        'BR' => 'A2Q3Y263D00KWC',
        'ES' => 'A1RKKUPIHCS9HS',
        'UK' => 'A1F83G8C2ARO7P',
        'FR' => 'A13V1IB3VIYZZH',
        'BE' => 'AMEN7PMS3EDWL',
        'NL' => 'A1805IZSGTT6HS',
        'DE' => 'A1PA6795UKMFR9',
        'IT' => 'APJ6JRA9NG5V4',
        'SE' => 'A2NODRKZP88ZB9',
        'PL' => 'A1C3SOZRARQ6R3',
        'EG' => 'ARBP9OOSHTCHU',
        'TR' => 'A33AVAJ2PDY3EV',
        'SA' => 'A17E79C6D8DWNP',
        'AE' => 'A2VIGQ35RCS4UG',
        'IN' => 'A21TJRUUN4KGV',
        'SG' => 'A19VAU5U5O7RUS',
        'AU' => 'A39IBJ37TRP1C6',
        'JP' => 'A1VC38T7YXB528',
    ];

    public const REPORT_STATUS_CANCELLED = 'CANCELLED';
    public const REPORT_STATUS_DONE = 'DONE';
    public const REPORT_STATUS_FATAL = 'FATAL';
    public const REPORT_STATUS_IN_PROGRESS = 'IN_PROGRESS';
    public const REPORT_STATUS_IN_QUEUE = 'IN_QUEUE';

    public const REPORT_COMPLETED_STATUS = [
        self::REPORT_STATUS_CANCELLED,
        self::REPORT_STATUS_DONE,
        self::REPORT_STATUS_FATAL,
    ];

    public const REPORT_TYPES = [
        'GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT' => 'GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT',
        'GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT' => 'GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT',
        'GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT' => 'GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT',
        'GET_VENDOR_SALES_REPORT' => 'GET_VENDOR_SALES_REPORT',
        'GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT' => 'GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT',
        'GET_VENDOR_TRAFFIC_REPORT' => 'GET_VENDOR_TRAFFIC_REPORT',
        'GET_VENDOR_FORECASTING_REPORT' => 'GET_VENDOR_FORECASTING_REPORT',
        'GET_VENDOR_INVENTORY_REPORT' => 'GET_VENDOR_INVENTORY_REPORT',
        'GET_SALES_AND_TRAFFIC_REPORT' => 'GET_SALES_AND_TRAFFIC_REPORT',
        'GET_FLAT_FILE_OPEN_LISTINGS_DATA' => 'GET_FLAT_FILE_OPEN_LISTINGS_DATA',
        'GET_MERCHANT_LISTINGS_ALL_DATA' => 'GET_MERCHANT_LISTINGS_ALL_DATA',
        'GET_MERCHANT_LISTINGS_DATA' => 'GET_MERCHANT_LISTINGS_DATA',
        'GET_MERCHANT_LISTINGS_INACTIVE_DATA' => 'GET_MERCHANT_LISTINGS_INACTIVE_DATA',
        'GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT' => 'GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT',
        'GET_MERCHANT_LISTINGS_DATA_LITE' => 'GET_MERCHANT_LISTINGS_DATA_LITE',
        'GET_MERCHANT_LISTINGS_DATA_LITER' => 'GET_MERCHANT_LISTINGS_DATA_LITER',
        'GET_MERCHANT_CANCELLED_LISTINGS_DATA' => 'GET_MERCHANT_CANCELLED_LISTINGS_DATA',
        'GET_MERCHANTS_LISTINGS_FYP_REPORT' => 'GET_MERCHANTS_LISTINGS_FYP_REPORT',
        'GET_PAN_EU_OFFER_STATUS' => 'GET_PAN_EU_OFFER_STATUS',
        'GET_MFN_PAN_EU_OFFER_STATUS' => 'GET_MFN_PAN_EU_OFFER_STATUS',
        'GET_REFERRAL_FEE_PREVIEW_REPORT' => 'GET_REFERRAL_FEE_PREVIEW_REPORT',
        'GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING' => 'GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING',
        'GET_ORDER_REPORT_DATA_INVOICING' => 'GET_ORDER_REPORT_DATA_INVOICING',
        'GET_ORDER_REPORT_DATA_TAX' => 'GET_ORDER_REPORT_DATA_TAX',
        'GET_ORDER_REPORT_DATA_SHIPPING' => 'GET_ORDER_REPORT_DATA_SHIPPING',
        'GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING' => 'GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING',
        'GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING' => 'GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING',
        'GET_FLAT_FILE_ORDER_REPORT_DATA_TAX' => 'GET_FLAT_FILE_ORDER_REPORT_DATA_TAX',
        'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL' => 'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL',
        'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL' => 'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL',
        'GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE' => 'GET_FLAT_FILE_ARCHIVED_ORDERS_DATA_BY_ORDER_DATE',
        'GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL' => 'GET_XML_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL',
        'GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL' => 'GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL',
        'GET_FLAT_FILE_PENDING_ORDERS_DATA' => 'GET_FLAT_FILE_PENDING_ORDERS_DATA',
        'GET_PENDING_ORDERS_DATA' => 'GET_PENDING_ORDERS_DATA',
        'GET_CONVERGED_FLAT_FILE_PENDING_ORDERS_DATA' => 'GET_CONVERGED_FLAT_FILE_PENDING_ORDERS_DATA',
        'GET_XML_RETURNS_DATA_BY_RETURN_DATE' => 'GET_XML_RETURNS_DATA_BY_RETURN_DATE',
        'GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE' => 'GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE',
        'GET_XML_MFN_PRIME_RETURNS_REPORT' => 'GET_XML_MFN_PRIME_RETURNS_REPORT',
        'GET_CSV_MFN_PRIME_RETURNS_REPORT' => 'GET_CSV_MFN_PRIME_RETURNS_REPORT',
        'GET_XML_MFN_SKU_RETURN_ATTRIBUTES_REPORT' => 'GET_XML_MFN_SKU_RETURN_ATTRIBUTES_REPORT',
        'GET_FLAT_FILE_MFN_SKU_RETURN_ATTRIBUTES_REPORT' => 'GET_FLAT_FILE_MFN_SKU_RETURN_ATTRIBUTES_REPORT',
        'GET_SELLER_FEEDBACK_DATA' => 'GET_SELLER_FEEDBACK_DATA',
        'GET_V1_SELLER_PERFORMANCE_REPORT' => 'GET_V1_SELLER_PERFORMANCE_REPORT',
        'GET_V2_SELLER_PERFORMANCE_REPORT' => 'GET_V2_SELLER_PERFORMANCE_REPORT',
        'GET_PROMOTION_PERFORMANCE_REPORT' => 'GET_PROMOTION_PERFORMANCE_REPORT',
        'GET_COUPON_PERFORMANCE_REPORT' => 'GET_COUPON_PERFORMANCE_REPORT',
        'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE' => 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE',
        'GET_V2_SETTLEMENT_REPORT_DATA_XML' => 'GET_V2_SETTLEMENT_REPORT_DATA_XML',
        'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2' => 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
        'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL' => 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL',
        'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING' => 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING',
        'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX' => 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_TAX',
        'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA' => 'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_SALES_DATA',
        'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_PROMOTION_DATA' => 'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_PROMOTION_DATA',
        'GET_FBA_FULFILLMENT_CUSTOMER_TAXES_DATA' => 'GET_FBA_FULFILLMENT_CUSTOMER_TAXES_DATA',
        'GET_REMOTE_FULFILLMENT_ELIGIBILITY' => 'GET_REMOTE_FULFILLMENT_ELIGIBILITY',
        'GET_AFN_INVENTORY_DATA' => 'GET_AFN_INVENTORY_DATA',
        'GET_AFN_INVENTORY_DATA_BY_COUNTRY' => 'GET_AFN_INVENTORY_DATA_BY_COUNTRY',
        'GET_LEDGER_SUMMARY_VIEW_DATA' => 'GET_LEDGER_SUMMARY_VIEW_DATA',
        'GET_LEDGER_DETAIL_VIEW_DATA' => 'GET_LEDGER_DETAIL_VIEW_DATA',
        'GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA' => 'GET_FBA_FULFILLMENT_CURRENT_INVENTORY_DATA',
        'GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA' => 'GET_FBA_FULFILLMENT_MONTHLY_INVENTORY_DATA',
        'GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA' => 'GET_FBA_FULFILLMENT_INVENTORY_RECEIPTS_DATA',
        'GET_RESERVED_INVENTORY_DATA' => 'GET_RESERVED_INVENTORY_DATA',
        'GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA' => 'GET_FBA_FULFILLMENT_INVENTORY_SUMMARY_DATA',
        'GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA' => 'GET_FBA_FULFILLMENT_INVENTORY_ADJUSTMENTS_DATA',
        'GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA' => 'GET_FBA_FULFILLMENT_INVENTORY_HEALTH_DATA',
        'GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA' => 'GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA',
        'GET_FBA_MYI_ALL_INVENTORY_DATA' => 'GET_FBA_MYI_ALL_INVENTORY_DATA',
        'GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT' => 'GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT',
        'GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA' => 'GET_FBA_FULFILLMENT_INBOUND_NONCOMPLIANCE_DATA',
        'GET_STRANDED_INVENTORY_UI_DATA' => 'GET_STRANDED_INVENTORY_UI_DATA',
        'GET_STRANDED_INVENTORY_LOADER_DATA' => 'GET_STRANDED_INVENTORY_LOADER_DATA',
        'GET_FBA_INVENTORY_AGED_DATA' => 'GET_FBA_INVENTORY_AGED_DATA',
        'GET_EXCESS_INVENTORY_DATA' => 'GET_EXCESS_INVENTORY_DATA',
        'GET_FBA_STORAGE_FEE_CHARGES_DATA' => 'GET_FBA_STORAGE_FEE_CHARGES_DATA',
        'GET_PRODUCT_EXCHANGE_DATA' => 'GET_PRODUCT_EXCHANGE_DATA',
        'GET_FBA_INVENTORY_PLANNING_DATA' => 'GET_FBA_INVENTORY_PLANNING_DATA',
        'GET_FBA_OVERAGE_FEE_CHARGES_DATA' => 'GET_FBA_OVERAGE_FEE_CHARGES_DATA',
        'GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA' => 'GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA',
        'GET_FBA_REIMBURSEMENTS_DATA' => 'GET_FBA_REIMBURSEMENTS_DATA',
        'GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA' => 'GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA',
        'GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA' => 'GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA',
        'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA' => 'GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA',
        'GET_FBA_RECOMMENDED_REMOVAL_DATA' => 'GET_FBA_RECOMMENDED_REMOVAL_DATA',
        'GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA' => 'GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA',
        'GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA' => 'GET_FBA_FULFILLMENT_REMOVAL_SHIPMENT_DETAIL_DATA',
        'GET_FBA_UNO_INVENTORY_DATA' => 'GET_FBA_UNO_INVENTORY_DATA',
        'GET_FLAT_FILE_SALES_TAX_DATA' => 'GET_FLAT_FILE_SALES_TAX_DATA',
        'SC_VAT_TAX_REPORT' => 'SC_VAT_TAX_REPORT',
        'GET_VAT_TRANSACTION_DATA' => 'GET_VAT_TRANSACTION_DATA',
        'GET_GST_MTR_B2B_CUSTOM' => 'GET_GST_MTR_B2B_CUSTOM',
        'GET_GST_MTR_B2C_CUSTOM' => 'GET_GST_MTR_B2C_CUSTOM',
        'GET_GST_STR_ADHOC' => 'GET_GST_STR_ADHOC',
        'GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT' => 'GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT',
        'GET_XML_VAT_INVOICE_DATA_REPORT' => 'GET_XML_VAT_INVOICE_DATA_REPORT',
        'GET_XML_BROWSE_TREE_DATA' => 'GET_XML_BROWSE_TREE_DATA',
        'GET_EASYSHIP_DOCUMENTS' => 'GET_EASYSHIP_DOCUMENTS',
        'GET_EASYSHIP_PICKEDUP' => 'GET_EASYSHIP_PICKEDUP',
        'GET_EASYSHIP_WAITING_FOR_PICKUP' => 'GET_EASYSHIP_WAITING_FOR_PICKUP',
        'RFQD_BULK_DOWNLOAD' => 'RFQD_BULK_DOWNLOAD',
        'FEE_DISCOUNTS_REPORT' => 'FEE_DISCOUNTS_REPORT',
        'GET_B2B_PRODUCT_OPPORTUNITIES_RECOMMENDED_FOR_YOU' => 'GET_B2B_PRODUCT_OPPORTUNITIES_RECOMMENDED_FOR_YOU',
        'GET_B2B_PRODUCT_OPPORTUNITIES_NOT_YET_ON_AMAZON' => 'GET_B2B_PRODUCT_OPPORTUNITIES_NOT_YET_ON_AMAZON',
        'GET_EPR_MONTHLY_REPORTS' => 'GET_EPR_MONTHLY_REPORTS',
        'GET_EPR_QUARTERLY_REPORTS' => 'GET_EPR_QUARTERLY_REPORTS',
        'GET_EPR_ANNUAL_REPORTS' => 'GET_EPR_ANNUAL_REPORTS',
    ];

    public const REPORT_FORMATS = [
        'GET_VENDOR_SALES_REPORT' => 'json',
        'GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT' => 'json',
        'GET_VENDOR_TRAFFIC_REPORT' => 'json',
        'GET_VENDOR_FORECASTING_REPORT' => 'json',
        'GET_VENDOR_INVENTORY_REPORT' => 'json',
    ];

    public const FEED_STATUS_CANCELLED = 'CANCELLED';
    public const FEED_STATUS_DONE = 'DONE';
    public const FEED_STATUS_FATAL = 'FATAL';
    public const FEED_STATUS_IN_PROGRESS = 'IN_PROGRESS';
    public const FEED_STATUS_IN_QUEUE = 'IN_QUEUE';

    public const FEED_COMPLETED_STATUS = [
        self::FEED_STATUS_CANCELLED,
        self::FEED_STATUS_DONE,
        self::FEED_STATUS_FATAL,
    ];

    public const FEED_TYPES = [
        'JSON_LISTINGS_FEED' => 'JSON_LISTINGS_FEED',
        'POST_PRODUCT_DATA' => 'POST_PRODUCT_DATA',
        'POST_INVENTORY_AVAILABILITY_DATA' => 'POST_INVENTORY_AVAILABILITY_DATA',
        'POST_PRODUCT_OVERRIDES_DATA' => 'POST_PRODUCT_OVERRIDES_DATA',
        'POST_PRODUCT_PRICING_DATA' => 'POST_PRODUCT_PRICING_DATA',
        'POST_PRODUCT_IMAGE_DATA' => 'POST_PRODUCT_IMAGE_DATA',
        'POST_PRODUCT_RELATIONSHIP_DATA' => 'POST_PRODUCT_RELATIONSHIP_DATA',
        'POST_FLAT_FILE_INVLOADER_DATA' => 'POST_FLAT_FILE_INVLOADER_DATA',
        'POST_FLAT_FILE_LISTINGS_DATA' => 'POST_FLAT_FILE_LISTINGS_DATA',
        'POST_FLAT_FILE_BOOKLOADER_DATA' => 'POST_FLAT_FILE_BOOKLOADER_DATA',
        'POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA' => 'POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA',
        'POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA' => 'POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA',
        'POST_UIEE_BOOKLOADER_DATA' => 'POST_UIEE_BOOKLOADER_DATA',
        'POST_STD_ACES_DATA' => 'POST_STD_ACES_DATA',
        'POST_ORDER_ACKNOWLEDGEMENT_DATA' => 'POST_ORDER_ACKNOWLEDGEMENT_DATA',
        'POST_PAYMENT_ADJUSTMENT_DATA' => 'POST_PAYMENT_ADJUSTMENT_DATA',
        'POST_ORDER_FULFILLMENT_DATA' => 'POST_ORDER_FULFILLMENT_DATA',
        'POST_INVOICE_CONFIRMATION_DATA' => 'POST_INVOICE_CONFIRMATION_DATA',
        'POST_EXPECTED_SHIP_DATE_SOD' => 'POST_EXPECTED_SHIP_DATE_SOD',
        'POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA' => 'POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA',
        'POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA' => 'POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA',
        'POST_FLAT_FILE_FULFILLMENT_DATA' => 'POST_FLAT_FILE_FULFILLMENT_DATA',
        'POST_EXPECTED_SHIP_DATE_SOD_FLAT_FILE' => 'POST_EXPECTED_SHIP_DATE_SOD_FLAT_FILE',
        'POST_FULFILLMENT_ORDER_REQUEST_DATA' => 'POST_FULFILLMENT_ORDER_REQUEST_DATA',
        'POST_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA' => 'POST_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA',
        'POST_FBA_INBOUND_CARTON_CONTENTS' => 'POST_FBA_INBOUND_CARTON_CONTENTS',
        'POST_FLAT_FILE_FULFILLMENT_ORDER_REQUEST_DATA' => 'POST_FLAT_FILE_FULFILLMENT_ORDER_REQUEST_DATA',
        'POST_FLAT_FILE_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA' => 'POST_FLAT_FILE_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA',
        'POST_FLAT_FILE_FBA_CREATE_INBOUND_PLAN' => 'POST_FLAT_FILE_FBA_CREATE_INBOUND_PLAN',
        'POST_FLAT_FILE_FBA_UPDATE_INBOUND_PLAN' => 'POST_FLAT_FILE_FBA_UPDATE_INBOUND_PLAN',
        'POST_FLAT_FILE_FBA_CREATE_REMOVAL' => 'POST_FLAT_FILE_FBA_CREATE_REMOVAL',
        'RFQ_UPLOAD_FEED' => 'RFQ_UPLOAD_FEED',
        'POST_EASYSHIP_DOCUMENTS' => 'POST_EASYSHIP_DOCUMENTS',
        'UPLOAD_VAT_INVOICE' => 'UPLOAD_VAT_INVOICE',
    ];

    public const FEED_FORMATS = [

    ];
}
