<?php

namespace lujie\otto;

use lujie\otto\api\OttoMarketApi;
use lujie\common\account\models\Account;
use yii\base\InvalidConfigException;

/**
 * This class is autogenerated by the OpenAPI gii generator
 */
class OttoRestClientFactory extends BaseOttoRestClientFactory
{

    /**
     * @param Account $account
     * @return OttoMarketApi|BaseOttoRestClient|null
     * @throws InvalidConfigException
     */
    public function getOttoMarketApi(Account $account): OttoMarketApi|BaseOttoRestClient|null
    {
        return $this->createClient(OttoMarketApi::class, $account);
    }

}
